### ISSUE TITLE
Attribute defined in the header are not processed

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/jekyll-asciidoc#1]
When we add the following attributes to an asciidoctor document, they are not processed and in this case, the TOC is not displayed in the HTML page : 

```

---
layout: default
title: GPE - Fuse Training Offering
documentationExpanded: false
postsExpanded: false

---
= Camel Training
Charles Moulliard
2013-10-06
:toc:
:toc-title: Chapters
```

**Comment by shaunlebron** [comment]
Neither of the options mentioned worked for me, but this did:

```
:toc: macro

toc::[]
```

**Comment by mojavelinux** [comment]
As of Asciidoctor 1.5.x, there are two options that work in this mode.

* `:toc: preamble`
* `:toc: macro`

The former only works if you document has a preamble (text before the first section). Your safest bet is `:toc: macro` as it allows you to place the toc where you want it.
