### ISSUE TITLE
AsciiDoc-set variables not resolving in Jekyll/Liquid

### ISSUE THREAD

**Issue by briandominick** [asciidoctor/jekyll-asciidoc#129]
I'm just about to soft launch my first Jekyll-Asciidoc site, and I suddenly realize the Liquid templates are no longer resolving page variables set in AsciiDoc templates. I must have changed a setting or disrupted something, but I can't figure it out. I did have it working.

If I set `:page-permalink: /my-page`, it does not pass to the build or the Liquid templates. If I prepend the file with the same var as front matter
```
---
permalink: /my-page
---
```
my permalinks start working again. What might I have done to cause this not to work? I have removed and reinstalled jekyll-asciidoc (2.0.1), re-run the `bundle install` -- everything else is working but passing variables outside AsciiDoc files.

**Comment by briandominick** [comment]
This problem extends to `:toc: macro` and `toc::[]` as well -- I can't get a TOC to appear.

**Comment by mojavelinux** [comment]
I'll look into this. A lot has changed recently and I you may be discovering something I've overlooked. I need to dig deeper.

Keep in mind, once 2.1.0 is released, you'll be able to put the toc anywhere in your Liquid template using:

```
{{ page.document | tocify_asciidoc }}
```

(That may not be what you are trying to do, just letting you know).

**Comment by mojavelinux** [comment]
I just verified that, if set up correctly, this should work in a new site.

I have a sneaking suspicion that the problem is that Jekyll is selecting a different layout than what you expect. The resolution of the layout has changed. See the following section:

https://github.com/asciidoctor/jekyll-asciidoc#specifying-a-layout

If you don't specify a layout, then it uses "_layouts/post.html" for posts, "_layouts/page.html" for pages and "_layout/<collection name>.html" for other collections. If that file cannot be found, it uses "_layouts/default.html".

Could you share your site source or show your _config.yml, the source of the AsciiDoc page and the contents of your layout?

**Comment by briandominick** [comment]
Hey Dan thanks for responding so quickly! The content of my project is internal docs for our engineering department, so I have to be careful what I share. I'm using the [Jekyll Documentation Theme](https://github.com/tomjohnson1492/documentation-theme-jekyll), so I've got a lot of template files.

Layout selection is working. I can make other changes to the template files and see what to expect. I'm declaring default templates in `_config.yml` in addition to in my AsciiDoc header.

I'm happy to test with alternate templates. I'll dig around there. I just can't use a "new site" because I've been hacking away at these templates. You can't think of anything I might have done working only with `_config.yml`, AsciiDoc content files, and  HTML template files (Documentation Theme uses a wrapper template (`default.html`), the specific template (`page.html`), and then uses includes for navs, head/header/footer, etc. None of these is reading my AsciiDoc-set vars.

**Comment by briandominick** [comment]
So I've gone back to an old working copy I saved (luckily I make backups even when I'm not ready to commit). I'm having the same problem in my oldest backup as well, so this has been an issue I wasn't noticing for a while. No matter what I try, the only way I can affect the value of page variables in my Liquid templates (at least from my .adoc file) is by setting it in the front-matter header. (Which of course spoils my `.adoc` files.)

Here's what I'm getting.

My `index.adoc`:
```
---
foo: bar
---
= My Page Title
:page-bar: foo
```

In a `page.html`:
```
{{page.bar}} {{page.foo}}
```

Expected: foo bar
Output: bar

**Comment by briandominick** [comment]
I created a fresh site. Moved the `_config.yml` file as-is. Created a fresh `index.adoc` and moved just enough layout files in to make it work. Nothing more. And it does work. I can set any var in my `index.adoc` file and pass it to the layout templates. So, now I reconstruct my site piece by piece to see where the problem is introduced.

**Comment by briandominick** [comment]
Mystery solved. You may have documented this somewhere, but apparently if you're going to put page-scope vars in your AsciiDoc file for passing on to Jekyll/Liquid, you must place their definitions above any AsciiDoc includes. I thought I had tested this way before. As soon as there's an include, it breaks the head, and `:page.varname: value` designations don't make it into the scope. This was really poor troubleshooting on my part. Made a bad assumption based on memory.

**Comment by mojavelinux** [comment]
> As soon as there's an include, it breaks the head, and :page-varname: value designations don't make it into the scope.

That makes sense as I added an optimization to read the header.

Are there, by chance, any blank lines either before the include or in the include itself? The AsciiDoc header stops at the first blank line, so that could explain it. It's imperative that you not have any blank lines in content you want to be part of the header.

**Comment by mojavelinux** [comment]
Nice detective work, btw!

**Comment by briandominick** [comment]
Thanks for your help. This is working great.

We're building a platform for our internal (non-product) docs that we'll open source to other eng teams if we can make it work for us. I really appreciate the help, and I promise to give back. You're doing great stuff. I'm glad I've finally had cause to tell you. Your stuff normally just works. ;-)

There was no blank line before or after the include line. And that's a good demarcation point, I think -- I was kind of assuming it, without looking at your source. BUT, there are blank lines in the include. It's funny, I took out comments, thinking they might be doing it. But I bet it was the blank lines.

**Comment by mojavelinux** [comment]
Thanks @briandominick! Your comment means a lot to me. :blush: 

I certainly hope you're able to make the platform work for you and your team. If you need any advice, don't hesitate to reach out. I work with teams on a daily basis to help build this type of platform. That's one of the driving forces behind my work in Jekyll AsciiDoc.

I went ahead and added explicit wording to the README to draw attention to the scenario you encountered. Hopefully, that saves someone time in the future.

https://github.com/asciidoctor/jekyll-asciidoc#page-attributes

Good luck!

**Comment by mojavelinux** [comment]
> But I bet it was the blank lines.

Yep. When reading the document header, the parser stops at the first blank line. That's a change from older versions of the plugin, which would read the entire file and pick up page attributes defined outside the document header.

**Comment by briandominick** [comment]
Where would be the best place for us to chat about my project. I would definitely like to pick your brain.

As for the way you're handling setting Jekyll page-scope variables in AsciiDoc files, I think you're doing it right. These are AsciiDoc pages; I can't think of a scenario where a conditional or anything dynamic can change to set a page variable before after the heading that couldn't have been set in the heading (or before).

**Comment by mojavelinux** [comment]
You are welcome to join us in the Gitter channel at https://gitter.im/asciidoctor/asciidoctor. You can also e-mail me at dan at opendevise.io and we can chat about something more formal.

**Comment by briandominick** [comment]
I have joined. Very cool. Looking forward to sharing this project.
