### ISSUE TITLE
how to apply a style to an image?

### ISSUE THREAD

**Issue by tortoise74** [asciidoctor/jekyll-asciidoc#138]
Hi,
     I'm not clear on the proper way to appy styles to images embedded in an asciidoctor doc.
For example if I want to use the "img-circle" class (from bootstrap) via _includes in the html I can add:

```
<img src="{{ site.baseurl}}/images/someimage.gif" class="img-responsive img-circle" alt="hello world"  width="100" height="100"> 
```

Where do I put the class in the asciidoc source?
I was expecting something like:

```
[img-circle]
image:/images/someimage.gif[]
```

or

```
[.img-circle]
image:/images/someimage.gif[]
```

or:

```
image:/images/someimage.gif[img-circle]
```

or:

```
image:/images/someimage.gif[class=img-circle]
```

but none of these work.
It works fine with a passthrough block but that is perhaps little inelegant.
There is also the issue of what should happen if you try to render the same source using asciidoctor-pdf
or similar.

```
++++
<img src="/images/someimage.gif" class="img-responsive img-circle" alt="hello world" width="100" height="100"> 
++++
```

Currently I haven't even got this working in asciidoc-reveal.js slides.
The output html looks right but the image is rendered with a black border rather than following the img-circle style class.

I think some of my confusion is caused because attributes like:

```
[.text-left]
```

look like css styles and are rendered as such (becomes class="text-left") but this is not the general rule.

Regards,

Bruce.

**Comment by mojavelinux** [comment]
This really depends on whether you want a block image (standalone) or an inline image.

If you want a block image, you'd write it as follows:

```
[.img-circle]
image::/images/someimage.gif[]
```

If you want an inline image, the syntax is slightly different:

```
image:/images/someimage.gif[role=img-circle]
```

Pay attention to the number of colons.

**Comment by mojavelinux** [comment]
> It works fine with a passthrough block but that is perhaps little inelegant.

Your instinct is correct that a passthrough block should be used as a very last resort. It's kind of like ducktape.

**Comment by tortoise74** [comment]
Why is the syntax different for block and inline images? That seems unnecessarily confusing.

http://asciidoctor.org/docs/user-manual/#images has the slightly cryptic admonition:
   
	"The shorthand syntax for a role (.) can not yet be used with image styles. "

**Comment by mojavelinux** [comment]
> Why is the syntax different for block and inline images? That seems unnecessarily confusing.

It's the same for all macros. Block macros have two colons. Inline macros have one colon. That's how the processor knows the difference.

**Comment by tortoise74** [comment]
I also notice if you try to provide two roles for a block image:

  [.img-responsive .img-circle]
  image::/images/someimage.gif[]

you get:

    <img src="/images/someimage.gif" alt=".img-responsive .img-circle">

However:

    [role="img-responsive img-circle"]
    image::/images/someimage.gif[]

gives you both classes as:

    <div class="imageblock img-responsive img-circle">

and with a syntax consistent with the inline image one.

**Comment by mojavelinux** [comment]
Spaces are not permitted in the shorthand syntax for defining roles:

```
[.img-responsive.img-circle]
image::/images/someimage.gif[]
```

(This syntax is borrowed from Slim and Haml).

**Comment by tortoise74** [comment]
Unfortunately I still can't get it to work.
The pass-through gives me:

   <img src="/images/somegif.gif" class="image img-responsive img-circle" >

but using:

    [.img-circle]
    image::/images/someimage.gif[]

gives me:

    <div class="imageblock img-circle">
    <div class="content">
    <img src="/images/someimage.gif" alt="someimage">
    </div>
    </div>

and using:

    image:/images/someimage.gif[role="img-circle"]

gives me:

   <span class="image img-circle"><img src="/images/someimage.gif" alt="someimage"></span>

It seems the img-circle class must be applied to the img tag itself rather than an enclosing div or span tag.

**Comment by mojavelinux** [comment]
That's exactly how the built-in HTML is structured. Keep in mind, you can customize every last character of HTML that Asciidoctor produces by supplying a custom template.

See https://github.com/asciidoctor/jekyll-asciidoc#customizing-the-generated-html

**Comment by tortoise74** [comment]
One motivation for trying to add styles was to fix black borders appearing around images in reveal.js slides. I'm using:

    :revealjs_theme: white

Currently I can't even do that if I directly alter the html. I wonder if it comes from one of the stylesheets imported by default?

**Comment by tortoise74** [comment]
My html and css is still rusty as it is.
Customising the template requires me to learn slim, which is a different beast from liquid. I also need to learn ruby which I have by some sleight of hand avoided thus far (despite polyglotting on many other languages).
Its something I probably need to do eventually anyway but is there a short cut?

I wondered about writing a macro but I see there is no documentation for that yet
https://github.com/asciidoctor/asciidoctor.org/issues/443

I guess that would be ruby too?

**Comment by mojavelinux** [comment]
> I wondered about writing a macro but I see there is no documentation for that yet asciidoctor/asciidoctor.org#443

Yes, that would be Ruby.

**Comment by mojavelinux** [comment]
This issue isn't really related to the Jekyll AsciiDoc plugin. If you need further help, please open an issue in the Asciidoctor Reveal.js project. https://github.com/asciidoctor/asciidoctor-reveal.js
