### ISSUE TITLE
How to use syntax-highlighting for AsciiDoc(tor) code?

### ISSUE THREAD

**Issue by sboekhoff** [asciidoctor/jekyll-asciidoc#140]
The recommended code-highlighter is `Pygments.rb`. Unfortunately there seems to be no lexer for asciidoc code (btw the same is true for markdown; http://pygments.org/docs/lexers/#lexers-for-non-html-markup-languages)

I'd like to highlight

```asciidoc
= Title
:var: value
// comment

* item 1
* item 2
* item 3
```
using for example

```asciidoc
[source,asciidoc]
----
= Title
:var: value
// comment

* item 1
* item 2
* item 3
----
```
and get a result like:

![adoc](https://cloud.githubusercontent.com/assets/10683690/20970612/b1241bea-bc8e-11e6-9c35-5e28c3b54c44.png)

**Comment by mojavelinux** [comment]
That's correct. Pygments does not support syntax highlighting for AsciiDoc. This is a feature that's only available in highlight.js and the text editors (Atom, Brackets, etc). You can either use highlight.js or push for Pygments to add support for AsciiDoc.
