### ISSUE TITLE
Broken block id and role generation

### ISSUE THREAD

**Issue by tim-janik** [asciidoctor/jekyll-asciidoc#143]
The block ids and roles are not properly generated in the jekyll HTML output as described here:
  http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#block-id-role-and-options

Issues encountered:
- plain [[blockid]] is ignored if placed before a heading
- it seems [#blockid] is ignored
- [role="special"] if used before a heading might apply only to the paragraph *after* the heading

**Comment by mojavelinux** [comment]
Is there any chance you are trying to put these above the document title? I ask because the document title does not support a custom id and role. Only the subsequent section titles on the page.

Can you point me to an example site that demonstrates this issue?

**Comment by mojavelinux** [comment]
According to the tests (and my own manual verification), the IDs and roles on section titles do work in the Jekyll environment.

**Comment by tim-janik** [comment]
I think I was trying to apply roles to a title, yes. I'm sorry, I don't have the means to reproduce this now, I gave up on Jekyll quickly after.

**Comment by mojavelinux** [comment]
Well, the good news is that it triggered me to add support for a page ID, which I think will be a helpful feature.

**Comment by mojavelinux** [comment]
See 43200beb362f80a280a4d02ad4debb63bed2f350. I also added tests to verify the IDs are set properly.
