### ISSUE TITLE
[Docs] [README] GitLab CI

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [asciidoctor/jekyll-asciidoc#144]
GitLab does not require pages to be published on branch master. The .gitlab_ci.yml `only` parameter dictates when the runner runs.

See -
https://docs.gitlab.com/ee/pages/README.html#explore-the-contents-of-gitlab-ci-yml

Where it says:
"Be aware that Pages are by default branch/tag agnostic and their deployment relies solely on what you specify in .gitlab-ci.yml. If you don't limit the pages job with the only parameter, whenever a new commit is pushed to whatever branch or tag, the Pages will be overwritten..."

However, it should also be noted there is no CI or pages option for self-hosted CE version of GitLab; only EE installs or GitLab.com.

**Comment by ParaplegicRacehorse** [comment]
Oops. I just went to edit the README and submit a PR and noticed the assumes bit just before the. gitlab-ci.yml. I recommend this be changed to reflect the lack of need to publish in master, though, for separation from the rest of code in the case of project sites instead of group or personal sites

**Comment by mojavelinux** [comment]
I made a small change to your request. I definitely want to make this clear though. I'm also happy to link to that resource so the reader can find more information.
