### ISSUE TITLE
Page categories defined via :page-category: don't get added to site.categories

### ISSUE THREAD

**Issue by tkfu** [asciidoctor/jekyll-asciidoc#149]
I recently attempted to change over one of my documentation sites to using the new 2.0 method of defining page variables (`:page-foo:` instead of `foo:` in front matter), because it will improve reusability. Unfortunately, it broke my build.

Based on my octopress-debugger output, it's because the categories defined by `:page-category:` are getting added only to page.category, not site.categories. The build broke because I use site.categories in a liquid tag in my layout, and it tried to do a sort on a null object.

I did find a workaround, however: using `:page-categories: [bar]` adds the categories to site.categories the way it should. So this isn't currently an issue for me, but I thought I'd report it anyway, since the behaviour is inconsistent and the new method of defining page variables is now the recommended one.

I'd be happy to provide more logs or further information if needed.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. I didn't realize that Jekyll was merging category into categories (and tag into tags). The integrator will have to handle that when processing the AsciiDoc header.
