### ISSUE TITLE
Question: How to specify asciidoctor extensions ?

### ISSUE THREAD

**Issue by prudhomm** [asciidoctor/jekyll-asciidoc#150]
I am using jekyll-asciidoc to generate the website http://book.feelpp.org 
I would like to use asciidoctor extensions such as asciidoctor-bibtex, how do I specify the extensions I would like to use when running jekyll-asciidoc ?

It was not obvious to me while reading the documentation

**Comment by prudhomm** [comment]
The question is also related to asciidoctor/asciidoctor#2101

**Comment by mojavelinux** [comment]
You load Asciidoctor extension code just like you would any Jekyll plugin. The following page describes the different strategies.

https://jekyllrb.com/docs/plugins/#installing-a-plugin

The fastest way is to create a _plugins folder, add a file named asciidoctor-extension.rb to it, and populate it with the following code:

```ruby
require 'asciidoctor/extensions'

Asciidoctor::Extensions.register do
  treeprocessor do
    process do |document|
      puts "Processing #{document.attr 'docfile'}"
      nil
    end
  end
end
```

**Comment by mojavelinux** [comment]
If the extension is published as a gem, it's just a matter of adding it to the jekyll_plugins group in the Gemfile, just like you would with the plugin itself or asciidoctor-diagram.

**Comment by mojavelinux** [comment]
I've added this note to the README.
