### ISSUE TITLE
[gem/Ubuntu16.04] Installation failed: mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

### ISSUE THREAD

**Issue by xusdom** [asciidoctor/jekyll-asciidoc#151]
Hi,
First of all i like to thank you for this project that make things easier - especially on win.

I got an error while installing ascidoctor-jekyll:

 
When installing asciidoctor / asciidoctor-jekyll on a fresh created ubuntu-16.04 server installation failed because of missing headers for ruby:
```mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h ....```

After doing ```sudo apt-get install ruby-dev``` it works. 
Maybe it would be nice to put this into README.md.

Greetz,
xusdom

**Comment by mojavelinux** [comment]
I've added a note to the README. The Ruby development headers are required to install many gems (on MRI) and thus a standard part of gem installation. Instructions for how to install the Ruby development headers, so I just left it as a note in the in the README that this is a prerequisite.

**Comment by peykar** [comment]
The command that worked for me:
apt-get --reinstall install ruby

**Comment by bhaible** [comment]
That did not work for me. I needed `apt-get install ruby-dev`.

**Comment by mojavelinux** [comment]
It's going to depend on the distribution and how it packages Ruby. One way or another, you need the header / development files available.

**Comment by bappi2016** [comment]
try it for ubuntu 16.04      sudo apt-get --reinstall install ruby
