### ISSUE TITLE
Question: why is it downloading adoc pages?

### ISSUE THREAD

**Issue by adamatti** [asciidoctor/jekyll-asciidoc#154]
#Could someone please check why it is downloading the adoc page (and not processing as html)?
Url: https://adamatti.github.io/blog/
Thanks in advance

Update: it works fine on local machine

**Comment by mojavelinux** [comment]
It looks like the AsciiDoc Jekyll plugin is not enabled (based on the fact that the .adoc file is not being processed).

The server is offering to download the page because it's not an HTML page...but that's just an effect. The cause is that the page is not converted to HTML.

How are you publishing to GitHub Pages?

**Comment by adamatti** [comment]
Thanks for the fast response... I created a repo called blog, and a branch gh-pages
url: https://github.com/adamatti/blog/tree/gh-pages
Thanks in advance.

**Comment by mojavelinux** [comment]
GitHub does not use the AsciiDoc Jekyll plugin. You have to generate the site and push the output of Jekyll to the result to the GitHub Pages branch. Most people use Travis CI to automate this process. For example: https://github.com/asciidoctor/jekyll-asciidoc-quickstart

**Comment by mojavelinux** [comment]
I certainly wish that GitHub would allow the Jekyll AsciiDoc plugin to be used on their GitHub Pages build server.

**Comment by adamatti** [comment]
Hmm... now it started to make sense... I will try it now.

**Comment by adamatti** [comment]
Update: I just give up... jekyll + asciidoc + gh-pages is not a task for mortals...

**Comment by eshepelyuk** [comment]
@adamatti don't give up :)) maybe this could help
http://eshepelyuk.github.io/2014/10/28/automate-github-pages-travisci.html

**Comment by adamatti** [comment]
Ok... I will give one more shot...

**Comment by adamatti** [comment]
It worked, finally! http://adamatti.github.io/blog
Thanks @eshepelyuk!

**Comment by mojavelinux** [comment]
It makes me so happy to hear that! :tada: :champagne:
