### ISSUE TITLE
Using `gems` in _config.yml is now deprecated

### ISSUE THREAD

**Issue by ctargett** [asciidoctor/jekyll-asciidoc#159]
This is probably just a documentation issue, but with Jekyll 3.5.0, using `gems` in _config.yml is deprecated in favor of `plugins`. A warning is thrown when Jekyll runs: 

`Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.`

See https://github.com/jekyll/jekyll/pull/5130 for background.

**Comment by mojavelinux** [comment]
Thanks for the heads up!
