### ISSUE TITLE
Include default AsciiDoctor stylesheet

### ISSUE THREAD

**Issue by eshepelyuk** [asciidoctor/jekyll-asciidoc#16]
Is it possible with means of Jekyll plugin to include default CSS `asciidoctor-default.css` from AsciiDoctor GEM into generated HTML for better styling of AsciiDoc markup without need of manually find and include the CSS file into Jekyll templates.

**Comment by mojavelinux** [comment]
I believe that JAQ now fills this void. In addition, version 2.0.0 allows you to generate standalone HTML files, which will include the stylesheet by default.

**Comment by djencks** [comment]
A comment in the docs about specifying the stylesheets in a layout would be good, otherwise there's nothing to do here.
