### ISSUE TITLE
Stem notation support?

### ISSUE THREAD

**Issue by ctargett** [asciidoctor/jekyll-asciidoc#163]
We're using Jekyll to render our AsciiDoc files, with the jekyll-asciidoc plugin. One of our contributors needs to add content that includes stem notations, and noted that it wasn't rendered properly in his tests. 

I added `:page-stem:` to my front-matter, but it does nothing. I also tried simply `:stem:` with the same result. Is Asciidoctor's stem notation support also supported with jekyll-asciidoc? Should we use something else instead as a plugin or extension to Jekyll? Or, is there something I should add to my templates to allow the support?

**Comment by mojavelinux** [comment]
The correct attribute would be `stem`, since this is a behavior of the core parser.

But the stem support is an integration feature, which means it relies on MathJax to actually handle the equations. All the stem attribute does is process stem blocks and macros and wrap them in markup for MathJax. That means you need to add MathJax to your page template.

You can use the following as a reference:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L228-L249

**Comment by mojavelinux** [comment]
To tell that the stem feature is working, you should be able to observe that `stem:[x^2]` is replaced with `\$x^2\$`.

**Comment by ctargett** [comment]
Ah, OK - I see content converted from `asciimath:[sqrt(4) = 2].` to `\$sqrt(4) = 2\$.` so I can assume the stem markup part is working. I'll see what I can figure out for adding MathJax to my templates. Thanks.

**Comment by mojavelinux** [comment]
This could be something nice to add to the [quickstart](https://github.com/asciidoctor/jekyll-asciidoc-quickstart).

**Comment by ctargett** [comment]
I figured out how to add it in a relatively simple way. You may have suggestions for this that are better - I just taught myself some JS last week, so nowhere close to being an expert in it.

I added a new _include file "mathjax_support.html" that I cobbled together from Googling and from asciidoctor/asciidoctor.js#60. Then I added that to my "head.html" _include, and updated `_config.yml` to add the `stem:` attribute. Seems to look pretty good! 

Here's the contents of "mathjax_support.html" in case you have feedback:

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  messageStyle: "none",
  tex2jax: {
    inlineMath: [["\\(","\\)"]],
    displayMath: [["\\[","\\]"]],
    ignoreClass: "nostem|nolatexmath"
  },
  asciimath2jax: {
    delimiters: [["\\$","\\$"]],
    ignoreClass: "nostem|noasciimath"
  },
  TeX: {
      equationNumbers: {
        autoNumber: "AMS"
      }
    }
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>
```

**Comment by mojavelinux** [comment]
Nice work!

I'll transfer this information to the README for others who are looking to set it up. Thank you for sharing!

**Comment by mojavelinux** [comment]
I've transferred this information to the README.
