### ISSUE TITLE
How to use included adoc files without converting them as well?

### ISSUE THREAD

**Issue by pcolmer** [asciidoctor/jekyll-asciidoc#165]
I have some documentation that is being maintained by a separate team in asciidoctor format. As such, there are limitations on what I might be able to do in regards to altering the files ...

There is a file called users-guide.adoc. The end of the file looks like this:

    include::users-guide-packet.adoc[]
    include::users-guide-pktio.adoc[]
    include::users-guide-timer.adoc[]
    include::users-guide-crypto.adoc[]
    include::users-guide-tm.adoc[]
    include::users-guide-cls.adoc[]
    include::../glossary.adoc[]

I've configured asciidoctor thus:

    asciidoc: {}
    asciidoctor:
      base_dir: :docdir
      safe: unsafe

The included files are in the same directory as users-guide.adoc, except for glossary.adoc which is in the parent directory.

The problem I've got is that Jekyll with this plugin is generating output for ALL of these adoc files, but I only want it generated for users-guide.adoc.

Is there a simple way to get my desired outcome?

Thanks.

**Comment by mojavelinux** [comment]
The convention is to either begin the filename with an underscore or put the included files in a directory that starts with an underscore.

See https://github.com/asciidoctor/jekyll-asciidoc#creating-pages

There is currently no way to list files to be excluded from conversion or to specify an explicit list to be converted.

**Comment by mojavelinux** [comment]
> There is currently no way to list files to be excluded from conversion or to specify an explicit list to be converted.

I think Jekyll now supports excluding files, though I'm not sure if they can still be referenced. See Exclude at https://jekyllrb.com/docs/configuration/options/#global-configuration
