### ISSUE TITLE
Permission denied for asciidoctor-diagram

### ISSUE THREAD

**Issue by nfrankel** [asciidoctor/jekyll-asciidoc#170]
I'm using the `asciidoctor-diagram` extension but I believe this is more related to the `jekyll-asciidoctor` project. Feel free to relocate the issue wherever it might be relevant.

The extension nicely generates the diagram, when configured with the root (_i.e._ `:imagesdir: /`). However, whenever I try to use a different folder, it fails:

```
ERROR: Failed to generate image: Permission denied @ dir_s_mkdir - /svg
```

I've tried with different folders, to no avail. I also tried use the `verbose` command-line parameter without getting more information.

Thanks for your help.

**Comment by nfrankel** [comment]
I understood the issue, it's about the leading `/`. The configuration is about the filesystem at generation time, not the web server at runtime.

If I configure `:imagesdir:` to `assets/resources`, it works.
If I configure it to `:imagesdir:` to `/assets/resources`, it doesn't.

Hence, the overall configuration should be:

```
:imagesoutdir: my/path
:imagesdir: /my/path
```

Feel free to close the bug, I think it might still be useful to others.

**Comment by wessven** [comment]
For awareness: I followed these instructions, and I was finally able to get the diagram generated and placed in the correct location.  However, if I edit the file which generates the file and save it while running `jekyll serve`, then Jekyll seems to go into an infinite loop of regenerating the .svg file:

    Configuration file: /home/wessven/Sandbox/jekyll/myblog/_config.yml
                Source: /home/wessven/Sandbox/jekyll/myblog
           Destination: /home/wessven/Sandbox/jekyll/myblog/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
           Jekyll Feed: Generating feed for posts
                        done in 0.514 seconds.
     Auto-regeneration: enabled for '/home/wessven/Sandbox/jekyll/myblog'
        Server address: http://127.0.0.1:4000/
      Server running... press ctrl-c to stop.
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:02
                        _posts/2019-04-25-an-asciidoctor-test.adoc
           Jekyll Feed: Generating feed for posts
                        ...done in 0.407418476 seconds.
                        
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:03
                        assets/img/dot-example.svg
           Jekyll Feed: Generating feed for posts
                        ...done in 0.41863548 seconds.
                        
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:03
                        assets/img/dot-example.svg
           Jekyll Feed: Generating feed for posts
                        ...done in 0.418895928 seconds.
                        
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:04
                        assets/img/dot-example.svg
           Jekyll Feed: Generating feed for posts
                        ...done in 0.385898415 seconds.
                        
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:04
                        assets/img/dot-example.svg
           Jekyll Feed: Generating feed for posts
                        ...done in 0.407666232 seconds.
                        
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:05
                        assets/img/dot-example.svg
           Jekyll Feed: Generating feed for posts
                        ...done in 0.413507921 seconds.
                        
          Regenerating: 1 file(s) changed at 2019-04-26 22:50:05
                        assets/img/dot-example.svg
    ^C       Jekyll Feed: Generating feed for posts
    
I am guessing that this is a bug in Jekyll, but I am posting it here for posterity.  My configuration is:

    keep_files:
      - assets
    
    asciidoctor:
      safe: unsafe
      attributes:
        imagesdir: /assets/img
        imagesoutdir: assets/img

I'm using Ruby 2.6.0, Jekyll 3.8.5, asciidoctor 2.0.8 and asciidoctor-diagram 1.5.16.

**Comment by mojavelinux** [comment]
This happens, to my knowledge, because the generation of the image triggers the watcher, which then causes the image to be generated again (because it is cleaned).

In the 3.0.0 version of the plugin, I'll be looking into a cleaner integration with Asciidoctor Diagram out of the box (whether in code or documentation) to avoid these sorts of issues.

As for this issue, it is closed, so any further discussion should happen in a fresh issue. We don't develop on close issues.
