### ISSUE TITLE
Generate HTML Description

### ISSUE THREAD

**Issue by samcv** [asciidoctor/jekyll-asciidoc#173]
Forgive me if there is a way to do this, but currently I have a site with both markdown and asciidoc pages. The newest pages are in asciidoc as I prefer it greatly. But I noticed today that the pages generated from asciidoc do not have an HTML "description" field, which is often used by search engines. Markdown generated with Jekyll seems to take the first paragraph and use it as a page description.

Is there a way to enable or control the generated description of the page using jekyll-asciidoc? If there is a way already, having information in the README would be great. Thank you.

**Comment by mojavelinux** [comment]
Unlike the Markdown integration, the AsciiDoc plugin does not populate the description property automatically. However, you can define the description in the header as follows:

```
= Page Title
:page-description: Description of this page

main content
```

**Comment by mojavelinux** [comment]
We're also working on support for the excerpt. See #200.

**Comment by mojavelinux** [comment]
Here's another way to do it so you only have to type the description once.

```
= Page Title
:page-description: Description of this page

{page-description}

Additional content.
```

Since this is the preferred approach in AsciiDoc for content reuse, we won't likely implement the automatic description.
