### ISSUE TITLE
Problem with  asciidocify liquid filter and include

### ISSUE THREAD

**Issue by laemtl** [asciidoctor/jekyll-asciidoc#176]
Using the  asciidocify liquid filter in a custom template, I've got a lot of Unresolved directive in 'stdin' - include::xxx.adoc[] in the output.
Everything is working fine when I run jekyll serve\build.
Here is my file:

```
---
layout: null
---
{
  {% assign tags = site.data.tags %}

  {% for page in site.pages %}

    "{{ page.url | slugify }}": {
      "title": "{{ page.title | xml_escape }}",
      "content"  : "{{ page.content | asciidocify | strip_html | strip_newlines | escape | remove: "\" }}",
      "url": " {{ page.url | xml_escape }}",
      "documentation": "{{ tags.name }}",
      "version": "{{ tags.version }}"
    }
    {% unless forloop.last %},{% endunless %}
  {% endfor %}
}
```

Thank you community!

**Comment by laemtl** [comment]
It's working with absolute path. Ant chance it can work wit relative ones?

**Comment by mojavelinux** [comment]
Yes, you just need to set the `base_dir` to `:docdir` in your _config.yml file. Then, Asciidoctor will resolve the include relative to the parent document, as it normally does.

```yml
asciidoctor:
  base_dir: :docdir
```

For more information, see https://github.com/asciidoctor/jekyll-asciidoc#specifying-the-base-directory.

Btw, you don't have to use asciidocify if you are using `page.content` or `post.content`. That content will already be converted to HTML. You only need to use asciidocify when the content in the model contains unprocessed AsciiDoc.
