### ISSUE TITLE
How to define diagram images path for gitlab pages?

### ISSUE THREAD

**Issue by mingoal** [asciidoctor/jekyll-asciidoc#177]
I tried to follow the REAMDE instruction to output PlantUML diagram. Didn't find the way to define correct output images path. Anybody knows how to do it?

Code @ https://gitlab.com/Mingoal/jekylldiagram
The output page is @ 
https://mingoal.gitlab.io/jekylldiagram/jekyll/update/2018/05/18/sample.html

In this page, the image path starts '/images/' instead of '/jekylldiagram/images/'. Which causes the image is not shown.

If you know how to correct it, please give me a tip. Thanks in advance.

**Comment by mojavelinux** [comment]
This is indeed a deficiency. The plugin should be prepending the baseurl to the value of the imagesdir attribute when the imagesdir value is root-relative. I've submitted a patch to address this.
