### ISSUE TITLE
Liquid includes of templates with HTML code

### ISSUE THREAD

**Issue by rkratky** [asciidoctor/jekyll-asciidoc#180]
When my Jekyll page includes (using the Liquid `include` tag) a template with HTML code, the HTML code gets converted by the AsciiDoctor processor, thus not rendering the HTML code as expected. Example:

**page.adoc**
```
---
front matter
---

:page-liquid:

{% include file.html %}
```

**file.html**
```
<p>{{ site.time }}</p>
```
This renders as:
```
<p>2018-07-24 11:47:17 -0500</p>
```
But it would be great to have a way to instruct the plugin to render it as expected, i.e.:
```

2018-07-24 11:47:17 -0500

```
It can be achieved by using the passthrough macro, i.e., for example:
```
+++{% include file.html %}+++
```
But that seems clunky.

**Comment by mojavelinux** [comment]
Actually, it would be:

```
++++
{% include file.html %}
++++
```

This is by design per the AsciiDoc language. You are including HTML into AsciiDoc. AsciiDoc only allows raw HTML if included in a passthrough block.

I'll make a mention of this in the docs.

**Comment by mojavelinux** [comment]
Other approach would be to use a custom block macro in Asciidoctor, which itself would include the content into the document tree. That might look like:

```
liquid::file.html[]
```

**Comment by rkratky** [comment]
Thanks.

> `liquid::file.html[]`

That would be very nice.

**Comment by mojavelinux** [comment]
You're free to implement it using the Asciidoctor extension API. Here's an example to follow: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/gist-block-macro/extension.rb
