### ISSUE TITLE
Generated markup wraps content in presentational divs without ARIA role specified

### ISSUE THREAD

**Issue by strogonoff** [asciidoctor/jekyll-asciidoc#181]
It appears that ADoc plugin adds extra wrapping elements `<div class="paragraph">` to markup.

* This is not consistent with the way Jekyll renders Markdown (this means `jekyll-asciidoc` is not perfectly pluggable, if a site is migrated to adoc from markdown there‘s a chance styling would be broken due to this markup change).

* Divs lack `aria-role="presentation"` despite being apparently just wrappers.

**Comment by strogonoff** [comment]
@mojavelinux Thanks. Is there already a way to configure the jekyll-asciidoc plugin to use a different converter, such as https://github.com/jirutka/asciidoctor-html5s you recommended? I couldn’s see one from a quick scan of the README.

**Comment by strogonoff** [comment]
The `asciidoc.processor` option https://github.com/asciidoctor/jekyll-asciidoc#asciidoc looks promising though, does it point to a binary?

**Comment by mojavelinux** [comment]
> The asciidoc.processor option looks promising though, does it point to a binary?

No, that's essentially meaningless now. It used to do something, but now more.

The way you register a custom converter is:

* Require the library using the require mechanism
* Set the backend option to "html5s"

The backend auto-loads the converter based on name. I haven't tested this with the Jekyll plugin, but that's how it works in theory.

**Comment by mojavelinux** [comment]
In other words:

```
require: asciidoctor-html5s
asciidoctor:
  backend: html5s
```

**Comment by strogonoff** [comment]
Awesome. Given processor backend can be configured, a problem with one particular backend probably isn’t this plugin’s issue.

**Comment by strogonoff** [comment]
I’ll close this as I’d guess it’s not in the scope of the plugin, if there’re problems with backend support I’ll file that separately. Also I take back the complaint about `role="presentation"` (it’s preferred equivalent now is `role="none"`, and divs are that by default).
