### ISSUE TITLE
Unresolved directive - include

### ISSUE THREAD

**Issue by pcolmer** [asciidoctor/jekyll-asciidoc#182]
I'm processing a file written by other people, using this plugin to convert it for use with a Jekyll site.

The document consists of a primary file, users-guide.adoc, and then multiple files that are referenced by the primary file using the `include` directive, e.g.:

```
include::users-guide-packet.adoc[]
```

All of the .adoc files are in the same folder.

When Jekyll is asked to build the whole site, it doesn't complain but the generated Jekyll output for users-guide.adoc includes these messages:

```
Unresolved directive in users-guide.adoc - include::users-guide-packet.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-pktio.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-timer.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-crypto.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-ipsec.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-tm.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-cls.adoc[]
Unresolved directive in users-guide.adoc - include::users-guide-utilities-examples.adoc[]
```

Curiously, this include statement works:

```
include::../glossary.adoc[]
```

If I run `jekyll build -V`, I *do* see the errors from asciidoctor, and it reveals that it is looking in the wrong directory for the included files - it is looking in the directory *above* where users-guide.adoc is located … which makes the fact that including ../glossary.adoc works even more puzzling!

Moving the included files into the parent folder seems to solve the build errors, but I'm not entirely sure that is the optimal solution.

The users-guide file builds without errors or warnings if I use `asciidoctor users-guide.adoc` with the included files in the same folder as users-guide.adoc.

What do I need to do/change in order to get the included files to be included?

Thanks.

**Comment by mojavelinux** [comment]
Very likely you need to set the base/working directory. See https://github.com/asciidoctor/jekyll-asciidoc#specifying-the-base-directory

(chances are, you want `:docdir` as the value).
