### ISSUE TITLE
Partial CSS on asciidoc?

### ISSUE THREAD

**Issue by EdPrado4** [asciidoctor/jekyll-asciidoc#183]
Hello, I've been working with asciidoc for some months now, and I was wondering if it's possible to apply a custom CSS on a specific part of the page using the "role" sentence in the asciidoc file, in order to render something like this:

```
...
<p> Normal paragraph, no changes</p>
<p class="custom-p">my custom css paragraph </p>
...
```

Now, adding some complexity, I want to apply CSS style on a specific <td> on a table. In asciidoc my file would look like this:

```
[role="mycustomrole4tables"]
|====
[cols=2]
a| normal cell, no changes applied
a| normal cell, no changes applied
a| custom cell, I want to apply CSS <-------
a| normal cell, no changes applied
|====
```

Many thanks in advance.

**Comment by mojavelinux** [comment]
That's exactly what the role is for.

```
[.custom-p]
my custom css paragraph
```

will output

```
<div class="paragraph custom-p">
<p>my custom css paragraph</p>
</div>
```

Just add the necessary CSS to style it.

**Comment by EdPrado4** [comment]
Yeah, it works perfectly on a plain paragraph, but I want to customize a paragraph inside a table cell, on which I already defined a role. In this case, where should I put the role to affect only the table cell I want to change?

**Comment by mojavelinux** [comment]
You cannot add a role directly to a cell. However, you can add a role to a block inside of a table cell, as long as the table cell has the "a" style.

```
a|
[.custom-role]
custom cell, I want to apply CSS
```

If you need to apply CSS directly to a table cell, you can only do so using `td` and other built-in selectors in CSS (such as nth-child).

**Comment by EdPrado4** [comment]
Got it, it works! thank you very much for your support and fast response

**Comment by mojavelinux** [comment]
Yeah! I'm happy to hear that!
