### ISSUE TITLE
Why might top-level headers fail to render?

### ISSUE THREAD

**Issue by etsauer** [asciidoctor/jekyll-asciidoc#184]
My site no longer generates the `<h1>`  tag with the document title. Here's an example:

testdoc.adoc
```
---
---
= My top level header

Hello, here is some intro text

== Sub header

blah

== Another subtitle

etc.
```

Renders as:
```
<div class="large-9 columns" role="content">
  <div id="preamble">
    <div class="sectionbody">
      <div class="paragraph">
        <p>Hello, here is some intro text</p>
      </div>
    </div>
  </div>
  <div class="sect1">
    <h2 id="sub-header">Sub header</h2>
    <div class="sectionbody">
      <div class="paragraph">
        <p>blah</p>
      </div>
    </div>
  </div>
  <div class="sect1">
    <h2 id="another-subtitle">Another subtitle</h2>
    <div class="sectionbody">
      <div class="paragraph">
        <p>etc.</p>
      </div>
    </div>
  </div>
</div>
```

Gemfile:
```
source 'https://rubygems.org'
ruby '2.4.3'

gem 'jekyll', '>=3.8.4'
gem 'asciidoctor', '1.5.7.1'
gem 'html-proofer'
gem 'ffi', '1.9.23'
gem 'rack'


group :jekyll_plugins do
  gem "jekyll-asciidoc", '2.1.0'
end
```

**Comment by Gl4di4torRr** [comment]
+1

**Comment by mojavelinux** [comment]
First, you don't need the empty front matter at the top of the document anymore. This will do:

```
= My top level header

Hello
```

Second, the document title is not included in the body content by default. Instead, it gets put into the model. Somewhere in your layout you should have:

```
{{ page.title }}
```

If, on the other hand, you do want the doctitle to be included in the body content generated by Asciidoctor, set the following attribute in your _config.yml:

```yml
asciidoctor:
  attributes:
    showtitle: ''
```

**Comment by mojavelinux** [comment]
I took this up as a documentation issue. See https://github.com/asciidoctor/jekyll-asciidoc#showing-the-document-title

**Comment by etsauer** [comment]
Thanks @mojavelinux !

**Comment by etsauer** [comment]
@mojavelinux FYI... we hit this because we upgraded from Jekyll 2.x to 3x, and in the process decided to update most of our related modules to the latest versions. It would be helpful if there was something that made it into the migration docs.

**Comment by etsauer** [comment]
After doing some more looking, I actually don't think this is specifically a plugin issue, but more with the migration from Jekyll 2 to 3 as a whole... The older version of our site rendered the `<h1>` with just the `{{content}}` tag in a layout. When it stopped rendering, I went into  asciidoctor debug mode, thinking it had something to do with doctypes. I would think a change like that would be captured in the [jekyll upgrade doc](https://jekyllrb.com/docs/upgrading/2-to-3/) but I'm not seeing it.

**Comment by mojavelinux** [comment]
I looked back all the way to the origins of this plugin and I'm confident that it never included the `<h1>` tag directly in the content (e.g., `{{ content }}`) by default. It might have been that somewhere in your configuration you had that feature enabled, and it didn't get carried over when you migrated. But this would be very specific to your use case.

Jekyll core has nothing to do with this plugin, so we not expect those docs to mention anything about the behavior of this plugin. These are separate pieces of software.
