### ISSUE TITLE
Pass a synthetic page variable in posts and other AsciiDoc files to indicate that the source is in AsciiDoc

### ISSUE THREAD

**Issue by behrangsa** [asciidoctor/jekyll-asciidoc#189]
In my layout, I have a chunk of code that looks like this:

```
{{ page.title | markdownify }}
```

I want to support AsciiDoc posts too so that I can modify that code to:

```
{% if page.asciidoc %}
  {{ page.title | asciidocify }}
{% else %}
  {{ page.title | markdownify }}
{% endif %}
```

But looks like at the moment there's no such variable added to the `page` object out of the box.

As a workaround, we can pass `asciidoc: true` in the front-matter of posts, but having this built-in functionality built-in will prevent errors (e.g. forgetting to add the variable to the front matter).

**Comment by mojavelinux** [comment]
You can already check for the document property:

```
{% if page.document %}
  {{ page.title | asciidocify }}
{% else %}
  {{ page.title | markdownify }}
{% endif %}
```

However, I realize that's rather ambiguous. I could support the idea of adding a boolean property as well.
