### ISSUE TITLE
Attributes not set in included files

### ISSUE THREAD

**Issue by rkratky** [asciidoctor/jekyll-asciidoc#192]
When defining attributes in files included using `include::`, the attributes are not set. If the same attribute is defined in the parent file instead, it works as expected (and resolved in the included child file, too). For example:

`parent.adoc`:
```
:attribute: value

include::child.adoc[]
```
`child.adoc`:
```
{attribute}
```
This works as expected, i.e. the attrib. is resolved, and `value` is rendered in the resulting doc.

However:
`parent.adoc`:
```
include::child.adoc[]
```
`child.adoc`:
```
:attribute: value
{attribute}
```
Doesn't work. In this case, `{attribute}` is rendered.

**Comment by mojavelinux** [comment]
This test provides this works: https://github.com/asciidoctor/jekyll-asciidoc/blob/9bb7aae945302c5e3e2eea978951f95bb600db40/spec/jekyll-asciidoc_spec.rb#L1091-L1096

Feel free to reopen if you can provide a test case that does not work.
