### ISSUE TITLE
hardbreaks-option=@ is not global

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/jekyll-asciidoc#205]
reading the docs it states to enabled hardbreaks-option but still allow individual doc override you use:

```
asciidoctor:
  attributes:
  - hardbreaks-option=@
```

but when I do that no posts have this enabled.

Only if I do this do I see a change:

```
asciidoctor:
  attributes:
  - hardbreaks-option
```

Not sure which is the expected behavior but I would expect that if hardbreaks is enabled and only if the doc says something else would it be disabled.

What I'm seeing is that I  need to enable it in every doc to take effect - which isn't really useful to me :)

Thus I would suggest to update the readme to be more precise or try fix this behavior.

**Comment by mojavelinux** [comment]
What you're describing seems like a bug. That should be working. I'll try to track it down.

**Comment by mojavelinux** [comment]
The correct name of the attribute is `hardbreaks`, not `hardbreaks-option`.

Try this:

```yml
asciidoctor:
  attributes:
  - hardbreaks=@
```

(This is one of those attributes in Asciidoctor that doesn't follow a consistent name because it predated our global options naming pattern).

See https://asciidoctor.org/docs/user-manual/#line-breaks
