### ISSUE TITLE
Automatically promote specified AsciiDoc page attributes to Jekyll page variables

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#207]
There are times when you want to make certain AsciiDoc attributes available as page attributes without having to specify the page- prefix. Examples include description, keywords, and copyright. Although some of these are already promoted (e.g., author), the list should be configurable.

Proposed configuration:

```
asciidoc:
  implicit_page_attributes: description, keywords, copyright
```

Another way to accomplish this is to set asciidoc.page_attribute_prefix to empty string. However, that has the side effect of bringing in the kitchen sink (and making it hard to differentiate between page-oriented attributes and attributes used by the document itself). This way, attributes can be promoted more selectively.

**Comment by djencks** [comment]
I think it's clearer to describe this as promoting page attributes (and AsciiDoc concept) to page variables (a Jekyll concept).
