### ISSUE TITLE
add to lobby instruction

### ISSUE THREAD

**Issue by cup** [asciidoctor/jekyll-asciidoc#209]
i see some instruction here:

https://github.com/asciidoctor/jekyll-asciidoc#publishing-your-site

but i didnt see that anyone had actually posted an issue on the pages repo yet,
so I did that. perhaps we could add for any interested to also post their
support on the issue?

**Comment by cup** [comment]
https://github.com/asciidoctor/jekyll-asciidoc/issues/209
https://github.com/asciidoctor/jekyll-asciidoc/issues/26
https://github.com/github/pages-gem/issues/624

**Comment by mojavelinux** [comment]
From what I've been told, GitHub doesn't take into account the number of comments or likes on the issue. They only count emails to support, which by their nature are not public.

**Comment by mojavelinux** [comment]
If you'd like to updated the instructions, please submit a proposal.
