### ISSUE TITLE
Jekyll AsciiDoc gem broken

### ISSUE THREAD

**Issue by JensKuehnel** [asciidoctor/jekyll-asciidoc#21]
Following the documentation the command of 'gem install jekyll-asciidoc' is telling me "invalid gem"
The completed output is:
```
$ gem install -V jekyll-asciidoc
HEAD https://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
HEAD https://s3.amazonaws.com/production.s3.rubygems.org/latest_specs.4.8.gz
304 Not Modified
ERROR:  Could not find a valid gem 'jekyll-asciidoc' (>= 0) in any repository
HEAD https://rubygems.org/prerelease_specs.4.8.gz
302 Moved Temporarily
HEAD https://s3.amazonaws.com/production.s3.rubygems.org/prerelease_specs.4.8.gz
200 OK
GET https://rubygems.org/prerelease_specs.4.8.gz
302 Moved Temporarily
GET https://s3.amazonaws.com/production.s3.rubygems.org/prerelease_specs.4.8.gz
200 OK
HEAD https://rubygems.org/specs.4.8.gz
302 Moved Temporarily
HEAD https://s3.amazonaws.com/production.s3.rubygems.org/specs.4.8.gz
304 Not Modified
ERROR:  Possible alternatives: jekyll-pandoc, jekyll-pseudo, jekyll-archives, asciidoc, jekyll-cdn
```

**Comment by eshepelyuk** [comment]
Tried to execute `gem install` (on Windows) and got following
```
jk@KIPARISUM /d/projects/eshepelyuk.github.io (jekyll)
$ gem install jekyll-asciidoc
ERROR:  Could not find a valid gem 'jekyll-asciidoc' (>= 0) in any repository
ERROR:  Possible alternatives: jekyll-pandoc, jekyll-pseudo, jekyll-archives, asciidoc, jekyll-cdn
```

Software versions (still on Windows)
```
jk@KIPARISUM /d/projects/eshepelyuk.github.io (jekyll)
$ ruby --version && gem --version
ruby 2.1.3p242 (2014-09-19 revision 47630) [i386-mingw32]
2.4.5
```

**Comment by paulrayner** [comment]
Jekyll-Asciidoc has been published to RubyGems as a prerelease gem (
https://rubygems.org/gems/jekyll-asciidoc), so add '--pre' when you do the
install:

     gem install jekyll-asciidoc --pre

This should work. I can update the version number if @mojavelinux gives the
ok, but I wanted to at least get it out in the wild as-is.

Paul.

**Comment by paulrayner** [comment]
Jekyll-Asciidoc has been published to RubyGems as a prerelease gem (
https://rubygems.org/gems/jekyll-asciidoc), so add '--pre' when you do the
install: `gem install jekyll-asciidoc --pre`.

This switch worked for me. I'll update the version number if @mojavelinux gives the
ok, but I wanted to at least get it out in the wild as-is.

**Comment by mojavelinux** [comment]
> I'll update the version number if @mojavelinux gives the ok, but I wanted to at least get it out in the wild as-is.

Excellent work! If @eshepelyuk can confirm it works, I'd say go for 1.0.0!

**Comment by eshepelyuk** [comment]
Works for me both locally and on `TravisCI`

**Comment by paulrayner** [comment]
v.1.0.0 has been released. Yay! I wrote an announcement on my blog at http://thepaulrayner.com/blog/2015/01/05/jekyll-asciidoc-gem-published.

**Comment by mojavelinux** [comment]
:beers: 

Great job guys! Thanks for making this happen!
