### ISSUE TITLE
delimit custom css classes

### ISSUE THREAD

**Issue by EdPrado4** [asciidoctor/jekyll-asciidoc#210]
Hello.

I'm trying to define nested css classes in my asciidoc, I need to define nested custom classes, i.e `roles` inside a `role` but I don't know how to limit the parent `role`. I'm having trouble understanding the scope of custom roles, where does it begin and end. Is there any way to limit the scope of custom roles, as for example in source is `----` is there a role equivalent to set a distribution like this?:

```
[role ="parent-role"]
-----[begin parent scope]-----

[role="children-role-1"]

[role="children-role-2"]

...

[role="children-role-n"]
-----[end parent scope]-----
```

**Comment by mojavelinux** [comment]
This is an AsciiDoc question.

You can nest elements in AsciiDoc using the open block. However, it only gives you one level.

```
[.parent]
--
[.child-1]
this is child 1

[.child-2]
this is child 2
--
```

Until unlimited nesting of open blocks is supported, you could use example blocks to nest blocks, which do support unlimited levels (by varying the length of the block delimiter).

**Comment by mojavelinux** [comment]
For more help with the AsciiDoc syntax, please consider asking questions like this in either the gitter channel (https://gitter.im/asciidoctor/asciidoctor) or on the discussion list (http://discuss.asciidoctor.org).

**Comment by djencks** [comment]
Asciidoctor discussion is now at https://asciidoctor.zulipchat.com/#.
