### ISSUE TITLE
Admonition blocks are not marked up semantically

### ISSUE THREAD

**Issue by strogonoff** [asciidoctor/jekyll-asciidoc#211]
Currently they appear to be marked up as tables. Should `jekyll-asciidoc` format admonition blocks more semantically? For example, as `<aside>`s.

**Comment by mojavelinux** [comment]
The Jekyll plugin doesn't provide a converter. That change would need to happen in core. In fact, it's already been proposed for the next feature release. See https://github.com/asciidoctor/asciidoctor/issues/242

I welcome your proposal for the correct semantics to use for that block.

Keep in mind, you also have the option of overriding the built-in converter to apply customizations to it. While that's not as ideal as having proper semantics out of the box, it gives you the control.

**Comment by strogonoff** [comment]
Thank you @mojavelinux!

**Comment by mojavelinux** [comment]
As this issue is not relevant for this plugin, I'm closing.

You can modify the template used to convert admonitions, which would allow you to use whatever HTML you want. See https://github.com/asciidoctor/jekyll-asciidoc#customizing-the-generated-html
