### ISSUE TITLE
dynamic qanda section

### ISSUE THREAD

**Issue by EdPrado4** [asciidoctor/jekyll-asciidoc#212]
Hello all.

I'm having troubles with a  qanda section on an interview-like post, I'd like to either remove the automatic enumeration, replace it with bullets, or manually set the number before the question, I have a text structure similar to this:

```
[qanda]
*question 1*::
  answer 1

Text related to Q1 but outside the scope of Q1.

 [qanda]
resets to Q1!
*question 2*::
answer 2
```
Is there any way to do this? 

Many thanks in advance

**Comment by mojavelinux** [comment]
This is an AsciiDoc question. You need to use a list continuation to prevent the list from breaking. See https://asciidoctor.org/docs/user-manual/#list-continuation

Here's how that would look:

```
[qanda]
question 1::
answer 1
+
Text related to Q1 but outside the scope of Q1.

question 2::
answer 2
```

**Comment by mojavelinux** [comment]
Please reopen if you need more information.
