### ISSUE TITLE
Document the asciidoctor 'data-uri' option more clearly

### ISSUE THREAD

**Issue by kornysietsma** [asciidoctor/jekyll-asciidoc#217]
It would be great if the option of setting the `data-uri` flag was more obvious to users - probably something in the Readme like:

---
## Using inline images

Instead of generating images, AsciiDoctor and the Diagram plugin can use [data-uri](https://en.wikipedia.org/wiki/Data_URI_scheme) to embed images directly in the generated HTML.  This has some downsides - this won't work in ancient browsers, images can't be linked to directly, and there are size limits (32K for IE8) - but this makes image generation simple and avoids needing to worry about preserving images.

You can set this per-page by adding `:data-uri:` to the document header, or globally by setting an attribute in your `_config.yml` :
```
asciidoctor:
  attributes:
  - data-uri=@
```

See [the Asciidoctor docs](https://asciidoctor.org/docs/user-manual/#managing-images) for more details.

---

 (I spent quite some time trying to follow the instructions and gist and the like to get it working using embedded images - inline images is a _much_ simpler approach and bypasses all that monkeypatching and configuration-fiddling stuff!)

**Comment by mojavelinux** [comment]
I like the idea. I welcome your PR to add this section to the README. Thanks in advance!

**Comment by djencks** [comment]
I'm revising the README into an Antora site on https://github.com/djencks/jekyll-asciidoc/tree/issue-238-antora-manual, so the PR wouldn't apply as-is.
I've incorporated the suggested content and extended it, in particular explaining a bit about the svg options.
Currently this is https://github.com/djencks/jekyll-asciidoc/commit/38dfe072c269720318f8de075a57268cb305fd9f but it may well get a new hash from more modifications or rebasing.

**Comment by djencks** [comment]
The Antora based site isn't published yet, but this content is in it for when it does get published.
