### ISSUE TITLE
No anchors generated for <h1>

### ISSUE THREAD

**Issue by rosieyohannan** [asciidoctor/jekyll-asciidoc#219]
When building my jekyll site no anchors are being created for h1 headings. I was expecting anchors to be generated in the same way as for h2, h3 etc... Is this expected?

h1
<img width="957" alt="Screenshot 2019-08-07 at 11 43 12" src="https://user-images.githubusercontent.com/24589403/62617213-48e01500-b909-11e9-899a-464f640a8e15.png">

h2
<img width="1008" alt="Screenshot 2019-08-07 at 11 43 23" src="https://user-images.githubusercontent.com/24589403/62617233-54cbd700-b909-11e9-8f63-daa235cf34da.png">

https://github.com/rosieyohannan/circleci-docs/tree/server/tranfer-content

**Comment by mojavelinux** [comment]
Yes, this is the expected behavior. By default, the doctitle is added by the page layout. So if you find the page layout, you should see where the `<h1>` is emitted. (Something like `<h1>{{ page.title }}</h1>`). You can add the HTML necessary to produce an anchor there.

(If you have the showtitle attribute enabled, disable it. You want the page layout to emit the `<h1>` element, not the Asciidoctor processor).

**Comment by mojavelinux** [comment]
Do you know which template from that repository is being used?

**Comment by rosieyohannan** [comment]
Oh I see! Thanks, yes it's this one I think: https://github.com/rosieyohannan/circleci-docs/blob/server/tranfer-content/jekyll/_layouts/classic-docs.html ... So I guess I need to add the anchor in here: https://github.com/rosieyohannan/circleci-docs/blob/6eb15a5d2d9b9f9646905b18d984eb78f2d85f38/jekyll/_layouts/classic-docs.html#L26 ... I'll give it a try! :-)

**Comment by rosieyohannan** [comment]
Oh no, this line: https://github.com/rosieyohannan/circleci-docs/blob/6eb15a5d2d9b9f9646905b18d984eb78f2d85f38/jekyll/_layouts/classic-docs.html#L28

**Comment by rosieyohannan** [comment]
Sorted, just added: `<h1 id="{{ page.title | downcase | split: " " | join: "-" }}">` to get cross refs to work to page titles in Jekyll and PDF. Thanks for your help again @mojavelinux !

**Comment by mojavelinux** [comment]
You bet!

If you feel this is resolved, please go ahead and close it.
