### ISSUE TITLE
broken development version

### ISSUE THREAD

**Issue by JensKuehnel** [asciidoctor/jekyll-asciidoc#22]
Using the Documentation I copied the jekyll-asciidoc.rb file to _plugins. Once under the name asciidoc_plugin.rb and once as  jekyll-asciidoc.rb.

Apperently you have to create the GEM and install it yourself.
I don't know if this is a doc bug or normal bug.

**Comment by paulrayner** [comment]
Release 1.0.0 of the gem has now been published. See http://thepaulrayner.com/blog/2015/01/05/jekyll-asciidoc-gem-published/ for details.
