### ISSUE TITLE
Tachyons Integration

### ISSUE THREAD

**Issue by EdPrado4** [asciidoctor/jekyll-asciidoc#222]
Hello there!

I've been recently working with [Tachyons](https://tachyons.io/) (i.e functional classes) and I wonder if asciidoc provides some sort of integration for tachyons, the `role` statement is quite useful, but it has some limitation regarding it's scope, since it affects the complete div and not a particular element, what if I'd like to:
- Customize different classes for different `<p>` in the same div?
- Customize the class of a, `<span> ` , `<a>`, or similar in the same div?
- Customize the width of a section? (this actually can be achieved with the `role` function )

My workaround here is to use html for this particular page, but I plan to extend the functional approach for styles on all my website, and most of it is built in asciidoc, so I will eventually face this issue. Any idea is appreciated

Many thanks in advance!

**Comment by mojavelinux** [comment]
This question is best asked either on the Asciidoctor discussion list (http://discuss.asciidoctor.org) or in the chat channel (https://gitter.im/asciidoctor/asciidoctor). It really pertains to Asciidoctor itself, not the jekyll-asciidoc plugin. As I hint, you'll want to be looking at the Asciidoctor extension API.

**Comment by mojavelinux** [comment]
This question is outside the scope of what this plugin provides. The chat is now located at https://chat.asciidoctor.org.
