### ISSUE TITLE
Front-matter attribute is not correctly passed to a jekyll plugin

### ISSUE THREAD

**Issue by matklad** [asciidoctor/jekyll-asciidoc#225]
I use `jekyll-redirect-from` plugin, and, while this works:

```
---
redirect_from: /2020/01/02/spinlocs-considered-harmful.html
---
= Spinlocks Considered Harmful
:sectanchors:
:experimental:
:page-liquid:
:page-layout: post
```

this doesn't

```
= Spinlocks Considered Harmful
:sectanchors:
:experimental:
:page-liquid:
:page-layout: post
:redirect_from: /2020/01/02/spinlocs-considered-harmful.html
```

I would expect both to function the same.

Source: https://github.com/matklad/matklad.github.io/blob/49e65f4b4d84d4e9262e194965aac7a257e2fcad/_posts/2020-01-02-spinlocks-considered-harmful.adoc

**Comment by wessven** [comment]
This is not a bug.  I use `jekyll-redirect-from` myself and don't have an issue.  As per the `jekyll-asciidoctor` documentation:

> Any AsciiDoc attribute defined in the AsciiDoc document header whose name begins with page- gets promoted to a page variables. The part of the name after the page- prefix is lowercased and used as the variable name (e.g., page-layout becomes layout). The value is processed as YAML data (single-line form).

So you need to have

```
= Spinlocks Considered Harmful
:sectanchors:
:experimental:
:page-liquid:
:page-layout: post
:page-redirect_from: /2020/01/02/spinlocs-considered-harmful.html
```

**Comment by matklad** [comment]
Thanks @wessven, this is indeed the problem!
