### ISSUE TITLE
Should menu and UI macros work?

### ISSUE THREAD

**Issue by rosieyohannan** [asciidoctor/jekyll-asciidoc#232]
Should these two features: menu:View[Zoom > Reset] and btn[label] display correctly in rendered jekyll html output?

**Comment by mojavelinux** [comment]
There are two parts this. First is whether the macros themselves are processed. That's enabled by defining the `experimental` attribute in the Jekyll config (if you don't want have to set it per document). The second part is whether the resulting HTML is styled properly. That requires an addition to the stylesheet that you include with your site. You can snag these lines of CSS for a quick solution: https://github.com/asciidoctor/asciidoctor/blob/1cde78f91aca9b7c9ca542ad118f6a736a12c693/data/stylesheets/asciidoctor-default.css#L117-L128

It might be a good idea to include what I just wrote under this section in the README: https://github.com/asciidoctor/jekyll-asciidoc#circled-callout-numbers

**Comment by rosieyohannan** [comment]
I got this working with your suggestions. the formatting looks odd though, with down and right arrows between menu options:

<img width="387" alt="Screenshot 2020-07-17 at 12 02 08" src="https://user-images.githubusercontent.com/24589403/87779964-9e18ec00-c825-11ea-8061-152b3d278bae.png">

**Comment by mojavelinux** [comment]
Looks like there is some sort of conflict going on with existing styles in your site.

**Comment by rosieyohannan** [comment]
Thanks, I will investigate! 👀🤔
