### ISSUE TITLE
Upgrade to Asciidoctor 2+

### ISSUE THREAD

**Issue by djencks** [asciidoctor/jekyll-asciidoc#237]
An obvious step...

Ruby 2.3.x and jruby-9.1.17.0 seem to have stopped being fetchable in a working state, so dropping them from travis and appveyor CI configuration.

**Comment by djencks** [comment]
I wonder how GitHub linking between PRs and issues works.... PR #241 did not get linked, and did not close the issue when manually linked.

**Comment by mojavelinux** [comment]
You have to mention it in the description, not (just) the subject. It's one of my big peeves about GitHub. It's must more obvious to mention it in the subject, but they just don't agree. If it doesn't get linked automatically, you can do it manually using the sidebar.

**Comment by djencks** [comment]
I'm too used to GitLab :-)  Thanks for the tip!
