### ISSUE TITLE
Documentation: Front-matter misidentified

### ISSUE THREAD

**Issue by jcsalomon** [asciidoctor/jekyll-asciidoc#25]
Under [Creating Pages](https://github.com/asciidoctor/jekyll-asciidoc#creating-pages) there this text:
> IMPORTANT: The AsciiDoc file must have a Markdown-style front matter header or else it won't be recognized as a page.

The front-matter is YAML, not Markdown.

**Comment by eshepelyuk** [comment]
There is open PR #24, about plugin documentation changes.
I can also update front-matter section, if @mojavelinux and @paulrayner are OK with it.

**Comment by paulrayner** [comment]
Sounds good to me.

**Comment by eshepelyuk** [comment]
Pushed fix to PR #24, as soon as PR will be merged this issue should be auto resolved.

**Comment by mojavelinux** [comment]
@jcsalomon, thanks for pointing out that a clarification is needed here. And thanks @eshepelyuk for incorporating this change.

When I originally wrote "Markdown-style front matter", what I meant was "YAML front matter commonly found in Markdown files". Perhaps we can word it in that way.

Even better would be to link the words "YAML front matter" to the Jekyll documentation on the subject: http://jekyllrb.com/docs/frontmatter/

**Comment by eshepelyuk** [comment]
Added link to Jekyll site to PR #24

**Comment by mojavelinux** [comment]
:+1:
