### ISSUE TITLE
 include file not found

### ISSUE THREAD

**Issue by libinglong** [asciidoctor/jekyll-asciidoc#274]
When the collection dir is custom dir,the base_dir is wrong.So include file will be not found.
_config.yml
```yml
collections_dir: cols
```
![image](https://user-images.githubusercontent.com/38123153/154786629-3530de7c-9771-441e-bf4c-38751e7eef73.png)

![image](https://user-images.githubusercontent.com/38123153/154786645-00350b77-9a76-4788-8e89-973845dd8136.png)

**Comment by ericzolf** [comment]
Did you check https://github.com/asciidoctor/jekyll-asciidoc/issues/176#issuecomment-434529915 ? it solved my issue which very much looked like yours.
