### ISSUE TITLE
Custom Liquid Tag been displayed as plain HTML

### ISSUE THREAD

**Issue by vepo** [asciidoctor/jekyll-asciidoc#275]
I have some custom liquid tags that I was using with Markdown and it's working fine. But for `jekyll-asciidoc` it shows the HTML content as plain text. Is this a configuration problem? Or is this a real bug?

This is my custom liquid tag: https://gist.github.com/vepo/34e67af0abe81012395e87d142fe64fb
This is my gemfile: https://github.com/vepo/vepo.github.io/blob/source/Gemfile

For Markdown
![image](https://user-images.githubusercontent.com/353569/200934438-b8f0e6e0-5569-43bf-b379-f9c21eba0369.png)

For Asciidoc
![image](https://user-images.githubusercontent.com/353569/200934552-d4b53ebd-b963-4d0f-9a04-d9a0d00bd0c1.png)

**Comment by mattrighetti** [comment]
You have to enclose that in `++++`. This might help you out [:page-liquid:](https://github.com/asciidoctor/jekyll-asciidoc/blob/89b8f55f5312e4a0f1bca496bd9217d53d5b21dd/docs/modules/ROOT/pages/liquid.adoc)

**Comment by mojavelinux** [comment]
That's correct. To output HTML in AsciiDoc, it must be enclosed in a passthrough block. See https://docs.asciidoctor.org/asciidoc/latest/pass/pass-block/
