### ISSUE TITLE
Status of this plugin / repository

### ISSUE THREAD

**Issue by jcralbino** [asciidoctor/jekyll-asciidoc#280]
Hello
I was interested in n asciidoc and creating a single page file of Websites from this. Can someone provide me details if this extension is a good fit taking into consideration that the latest release was 5 years ago

Is this plugins still supported ?

**Comment by mojavelinux** [comment]
Please direct questions about usage and project status to the project chat at https://chat.asciidoctor.org. In particular, you can find statements here: https://asciidoctor.zulipchat.com/#narrow/stream/279656-dev-.F0.9F.9B.A0.EF.B8.8F/topic/seeking.20maintainer.20for.20jekyll-asciidoc
