### ISSUE TITLE
Create git tag for release

### ISSUE THREAD

**Issue by jirutka** [asciidoctor/jekyll-asciidoc#29]
There’s version 1.0.0 on RubyGems, but no tag `v1.0.0` in this repo.

**Comment by mojavelinux** [comment]
Thanks for pointing that out. That probably means the `rake release` task wasn't used for the release. We should definitely add it.

We should also document how to do a release in a releasing section in the README so we get it right in the future.

**Comment by jirutka** [comment]
The `release` task is already defined.

**Comment by mojavelinux** [comment]
I know, it just wasn't used.

I added an enhancement to create a discrete commit for the tag, which I like to use as it makes the history easier to understand. I also documented how to perform a release. See https://github.com/asciidoctor/jekyll-asciidoc/commit/f0da8e35592de946e58ee1a0132c4a8d4c997339.

**Comment by jirutka** [comment]
Creating an empty commit doesn’t make any sense for me, it creates just a noise in the repo history. The commit with version bump (i.e. change in the version.rb file) is IMHO perfectly sufficient for this.

You should also change the version number to something like `1.0.2.dev` after releasing a new version and it’s better to do it in a separate commit, so then you end up with three commits per release.

```
Bump version to 1.0.2
Release 1.0.2
Prepare for next development iteration
```

**Comment by mojavelinux** [comment]
Agreed on the version number bump.

If you think it's better not to create an empty release, I'm fine with that. I'll remove the extra logic then.

**Comment by jirutka** [comment]
Well, I personally don’t see any benefit for the empty commit and also haven’t seen it anywhere else. Why do you consider it easier to understand?

**Comment by mojavelinux** [comment]
I think it was all in how the commit messages are written. When I came into Asciidoctor, the commit message was "prepare for 1.5.2 release" and that was the commit that was tagged. I didn't like that the tag message said "prepare" and not just "release". Now I can see that we should just put the commit message we want in the release when updating the version number.

Thus, the README should propose a commit message format when setting the version number.

**Comment by jirutka** [comment]
> I didn't like that the tag message said "prepare" and not just "release".

I understand, I’ve also used to have exactly the same problem! This “Prepare for x.y.z” style is a (bad) habit from Maven. Then I’ve somewhere seen “Release x.y.z” and found it better. :smiley_cat:
