### ISSUE TITLE
Can the plugin detect and translate links from *.adoc into *.html links?

### ISSUE THREAD

**Issue by etsauer** [asciidoctor/jekyll-asciidoc#34]
While processing content,  I would like:
```
link:/path/to/file.adoc[Link Name]
```
to be translated to
```
<a href="/path/to/file.html">Link Name</a>
```

Can this be done currently?

**Comment by mojavelinux** [comment]
The right way to handle this is via inter-document xrefs. You'd enter it as:

```
<</path/to/file#,Link Name>>
```

In order for this to work, though, you have to use the development version of Asciidoctor (eventually 1.5.3).

Until then, you can type it as follows:

```
link:/path/to/file{outfilesuffix}[Link Name]
```

**Comment by mojavelinux** [comment]
The feature mentioned is now available in Asciidoctor, so I'm going to close this issue. For more information, see http://asciidoctor.org/docs/user-manual/#navigating-between-source-files.
