### ISSUE TITLE
Sidebar table of contents in Jekyll

### ISSUE THREAD

**Issue by TomSwan** [asciidoctor/jekyll-asciidoc#37]
When processed by Jekyll, `:toc: left` and `:toc: right` directives do not position tables of content in a sidebar as when the same document is processed by the stand-alone asciidoctor.

**Comment by mojavelinux** [comment]
Information for someone looking to implement this feature:

When using Asciidoctor 1.5.3, Asciidoctor will add the TOC to the top of the embedded document when the value is `left`, `right` or empty string. So the first requirement is to use Asciidoctor 1.5.3. It will then be necessary to add some CSS that honors the `toc` value and positions the TOC accordingly.

If the default HTML does not provide enough flexibility, a custom template for the embedded node can be used to modify it. (For an example, see https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/embedded.html.slim or https://github.com/asciidoctor/asciidoctor-backends/blob/master/haml/html5/embedded.html.haml)

Here are a few sites to use as design reference:

* https://developers.openshift.com/en/getting-started-overview.html
* http://www.rubymotion.com/developers/guides/manuals/cocoa/getting-started

**Comment by mojavelinux** [comment]
Keep in mind that the default HTML generated for the html5 backend is just that, a default. Asciidoctor is designed to be extended and should be extended to make integrations like the Jekyll plugin work better.

**Comment by mojavelinux** [comment]
We could do something similar that we've done with Awestruct. We put the document object into the page context (i.e., `page.data`). You can then use that document to print a table of contents in the template anywhere outside of the content area.

Here's the patch we made to Awestruct: https://github.com/asciidoctor/asciidoctor.org/blob/f620320dbbe53ea6da778ae97d14a18839004540/_ext/awestruct_ext.rb#L8-L12

The problem is that the Converter interface in Jekyll doesn't give us access to the page context when the `convert` method is called. We'd need to load the full document into the data hash in the generator. The downside is that we parse the whole document twice.

**Comment by mojavelinux** [comment]
I think the right thing to do is to implement a toc filter for Liquid. That still requires that we store the document object in the payload so that the filter can access it.

**Comment by mojavelinux** [comment]
The reason I suggest the liquid filter is because, currently, Jekyll doesn't support template languages other than Liquid, so simply exposing the document object wouldn't be of much use as you can't invoke its API.

**Comment by mojavelinux** [comment]
We actually have a choice between a liquid filter and a liquid tag.

Here's how it would look as a filter:

```
{{ page.document | tocify_asciidoc }}
```

and with an explicit number of levels:

```
{{ page.document | tocify_asciidoc: 3 }}
```

(we may consider asciidoc_tocify as an alternate name)

Here's how it would look as a tag:

```
{% asciidoc_toc %}
```

and with an explicit number of levels:

```
{% asciidoc_toc 3 %}
```

I prefer the filter for a few reasons. First, it keeps the door open to use it on an auxiliary document. Second, filters have better support for arguments, whereas we have to parse the arguments supplied to a tag. Finally, with the parsed document available as `page.document`, it opens the door to other document transforms written as filters or using the object in a more capable template languages like Slim.

I only plan to output the toc starting at the outer `<ul>`. This gives maximum flexibility to the template author to arrange it as desired. It's even possible to check for an empty table of contents using the capture tag.

```
{% if page.document %}
{% capture toc %}{{ page.document | tocify_asciidoc }}{% endcapture %}{% if toc != '' %}<div class="toc">
{{ toc }}
</div>{% endif %}
{% endif %}
```

**Comment by mojavelinux** [comment]
@eshepelyuk @paulrayner @johncarl81 @mkobit How does this proposal look to you?

**Comment by eshepelyuk** [comment]
Both are OK for me :))

**Comment by mkobit** [comment]
:+1: for me as well. I think I would be more likely to use the filter.

**Comment by johncarl81** [comment]
The filter approach makes sense to me.  Looks good!

**Comment by paulrayner** [comment]
👍
