### ISSUE TITLE
Unable to display admonitions images

### ISSUE THREAD

**Issue by robjens** [asciidoctor/jekyll-asciidoc#39]
Hi Dan,

I tried to get the font-awesome icons to work in Jekyll Asciidoctor however I keep getting dead links pointing at the alleged images directory of the conventional (posts) filename e.g. `example.com/2015/01/01/images/note.png` which, doesn't exist. Since I don't get the idea Jekyll makes it easy to include post-specific assets this way, I was left but to try and get font-awesome to work.

I think the front-matter screws things up though... I couldn't get Deck.js + Jekyll + Asciidoctor to play nice either and had to resort to a build+launch script for the extra `asciidoctor -t templates` command. I tried a dozen variations of:

```
---
stuff: more stuff
---
= Foobar
:icons: font 

Some para starts here
```

Any pointer on how to proceed? I'm kinda lost atm and the png location seems baked in as a fallback without any option to change location from other than the document head (e.g. via `_config.yml` asciidoctor command line arguments) right?

**Comment by robjens** [comment]
Also, be advised: the location referenced in the `README` of this repo mentioned the location `lib/asciidoc_plugin.rb` but that file (no longer) exists, carrying the name of `jekyll-asciidoc.rb` currently. I assume this is the file needed (not version.rb in the subdirectory), however, it remains unclear if the intention is to _rename this file_ or if it should keep the current filename.

**Comment by mojavelinux** [comment]
Oops, looks like the README is out of date. You should be using this as a gem now, so there is no longer any need to move files around.

For an example, see https://github.com/asciidoctor/jekyll-asciidoc-quickstart

**Comment by mojavelinux** [comment]
It would be good to include a tip on how to get font-based icons setup in the README.

**Comment by robjens** [comment]
Ok I fixed it. Had to update to jekyll 3, remove a _config.yml entry (icons=fontawesome), tinkered a little bit and all of a sudden they appeared. I used the distributed gem 1.0.0 now, had a distributed earlier but I think it was an older version - this one works... Thanks for the prompt reply.

**Comment by robjens** [comment]
https://github.com/asciidoctor/jekyll-asciidoc-quickstart/blob/master/_config.yml#L9 That line is incorrect and prevented proper display of the icons me thinks...

**Comment by mojavelinux** [comment]
Correct. It should say `icons=font`.

Btw, I'm sending a big update to the README to cover all this.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/jekyll-asciidoc#supplemental-asciidoc-assets

**Comment by mojavelinux** [comment]
If you are using Jekyll 3, I highly recommend building the gem from the jekyll-asciidoc repository and using that since it has numerous fixes for Jekyll 3. We should have a new release out soon.
