### ISSUE TITLE
Automate release process with CI

### ISSUE THREAD

**Issue by mkobit** [asciidoctor/jekyll-asciidoc#45]
Releases should be completely (or as much as possible) automated by a CI system. 

The current release process is mostly manual. This leads to slow release cycles that are prone to error. The current process is well documented in https://github.com/asciidoctor/jekyll-asciidoc/issues/36.

I am surely missing some items, but here is current list of actions for a release (assuming access to the [`jekyll-asciidoc` RubyGem](https://rubygems.org/gems/jekyll-asciidoc) and this repository):
1. Update version in _lib/jekyll-asciidoc/version.rb_
2. Commit and run `rake release`. This accomplishes a few things:
   - Creates and pushes a Git tag
   - Pushes commit up to remote
   - Publishes gem to  [`jekyll-asciidoc` RubyGem](https://rubygems.org/gems/jekyll-asciidoc)
3. Update version in _lib/jekyll-asciidoc/version.rb_ for next release
4. Create a [Github release](https://github.com/asciidoctor/jekyll-asciidoc/releases) for the tag
   - Identify relevant issues since last release
   - Tag with relevant milestone
   - Close open issues
5. Close milestone

In my opinion, I think trying to achieve a level of automated releases similar to how the [_spinnaker/deck_](https://github.com/spinnaker/deck) would be awesome.
###### Related issues
- "Releases should be performed by the CI server (releases should be fully automated)" - https://github.com/asciidoctor/asciidoctor/issues/1565
- "publishing Jekyll 3 updates" - https://github.com/asciidoctor/jekyll-asciidoc/issues/36

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
Here's a helpful article on the topic of releasing in one click: http://www.yegor256.com/2014/08/26/publish-to-rubygems.html

**Comment by mojavelinux** [comment]
I have good news. @ldez has figured out how to get Travis CI to do a release (at least for apm packages). I think we can build on that work for this issue. See:

* https://github.com/ldez/travis-continuous-delivery-atom-publish
* https://github.com/asciidoctor/atom-autocomplete-asciidoc/issues/2

**Comment by mojavelinux** [comment]
Here's the manual release process I've been following:

* Resolve all issues filed against the current milestone in the issue tracker.
* Record all changes for this release in CHANGELOG.adoc and set release date and released by:

      == X.Y.Z (YYYY-MM-DD) - @username

* Verify copyright year is correct in README.adoc and LICENSE.adoc, updating if necessary.
* Drop `.dev` suffix from version in *lib/jekyll-asciidoc/version.rb*
* Add revision line to README.adoc with version and date:

      vX.Y.Z, YYYY-MM-DD

* Create a prepare release commit using:

      $ git commit . -m 'Prepare X.Y.Z release'

* Push commit to GitHub:
* Verify CI build passes at https://travis-ci.org/asciidoctor/jekyll-asciidoc.
* Create an empty release commit using:

      $ git commit --allow-empty -a -m 'Release X.Y.Z'

* Create git tag, push commits and tags to GitHub, build gem and publish to RubyGems.org:

      $ bundle exec rake release

* Close milestone in the issue tracker.
* Create a new release on GitHub for this tag and copy in changes from CHANGELOG.adoc using the following template:

      Executive summary.

      ### Changes

      * ...

      ### Distributions

      * [RubyGem (jekyll-asciidoc)](https://rubygems.org/gems/jekyll-asciidoc)

* Bump version in *lib/jekyll-asciidoc/version.rb* and add `.dev` suffix
* Remove revision line from README.adoc.
* Start development on next release using:

      $ git commit . -m 'Begin development on next milestone [skip ci]'

* Push commit to GitHub:

      $ git push origin master

**Comment by mojavelinux** [comment]
Travis can be configured to release a gem to RubyGems.org. See https://docs.travis-ci.com/user/deployment/rubygems/. I think I'm going to give that a try.

**Comment by mojavelinux** [comment]
Here's a script I hacked together to handle bumping the version and creating the release commits.

```
#!/usr/bin/bash

GEM_VERSION=`bundle exec ruby -e "print (Gem::Version.new Jekyll::AsciiDoc::VERSION).release"`
sed -i "/VERSION/s/'[^']\+'/'$GEM_VERSION'/" lib/jekyll-asciidoc/version.rb
sed -i "3i v$GEM_VERSION, `date +%Y-%m-%d`" README.adoc
git commit -a -m "Prepare $GEM_VERSION release"
git commit --allow-empty -m "Release $GEM_VERSION"
git tag -m "Version $GEM_VERSION" v$GEM_VERSION
git push --tags
sed -i "3d" README.adoc
GEM_VERSION=`bundle exec ruby -e "print (Gem::Version.new Jekyll::AsciiDoc::VERSION).segments.tap {|s| s[-1] += 1 }.join('.') + '.dev'"`
sed -i "/VERSION/s/'[^']\+'/'$GEM_VERSION'/" lib/jekyll-asciidoc/version.rb
git commit -m "Begin development on next version [skip ci]" .
git push
```

I find most of the release helper gems to be too complex and error prone.

**Comment by mojavelinux** [comment]
After I pushed the tag, Travis performed the release. It went off without a hitch (except for some reason Travis failed on one of the interim builds claiming the commit disappeared).

Now that Travis releases the gem, what's next is to have Travis create the tag. I'd like to be able to push a commit to master that triggers the release.sh script. We might want to consolidate some of the commits too so that we don't end up with so many interim commits.

I'm thinking something like:

```
initiate release [ci skip]
```

From there, Travis runs release.sh to create the release commit and switch back to the development version after.

This is where we need to setup the SSH key because we need to allow Travis to push to the repository.

**Comment by mojavelinux** [comment]
Interesting to note that Travis now has build stages which would allow the commit and deploy to happen in the same build. See https://docs.travis-ci.com/user/build-stages/deploy-rubygems/. I'm not sure if that will work for us, but it looks promising.

**Comment by mojavelinux** [comment]
This now done in GitHub Actions. The Release workflow drives a release starting from the web form.
