### ISSUE TITLE
Page title not assigned the value of doctitle when using Jekyll 3

### ISSUE THREAD

**Issue by eshepelyuk** [asciidoctor/jekyll-asciidoc#48]
I've noticed an issue when trying to migrate my blog from `Jekyll 2` to `Jekyll 3`.
To reproduce it I've created sample `Jekyll` site with `jekyll new` command and created a sample `AsciiDoc` page as described in plugin's _README_.

Assuming my page located at `_posts/2015-11-11-page11`, I expect to see its title ( extracted from `AsciiDoc` page title marked with `=` ) in post list.

But instead I see `Page11` as a page title. The same happens when I navigate to the page.

It seems `Jekyll` or this plugin doesn't  properly set neither `post,title` nor `page.title` after update to  `Jekyll 3`. Using `Jekyll 2.5.3` with the latest version of the plugin provides expected result, i.e. `Liquid` veriables `page.title` and `post.title` are populated from `AsciiDoc` 1st level header.

To overcome the issue it's possible to add `:title` attribute to the _Front Matter_ of each page, but I'd like to see previous behaviour, i.e. when that attribute was populated based on `AsciiDoc` document title.

Attached content of the sample project below.

[jekyll3.zip](https://github.com/asciidoctor/jekyll-asciidoc/files/228352/jekyll3.zip)

**Comment by mojavelinux** [comment]
At some point, Jekyll started assigning a default title to posts (using `Utils.titleize_slug`).

https://github.com/jekyll/jekyll/blob/v3.1.3/lib/jekyll/document.rb#L294-L295

This breaks our logic, which only assigns the title if not already specified.

https://github.com/asciidoctor/jekyll-asciidoc/blob/v1.0.1/lib/jekyll-asciidoc.rb#L120

There are a couple of things we can do.

1. Assign the title anyway if the AsciiDoc document has a doctitle (we'd need to check first)
2. Check if the title is equal to title that Jekyll generates (using `Utils.titleize_slug`). If that's the case, we can assume the title was automatically assigned and we should override it (again, if doctitle is set)
3. We could monkeypatch `Utils.titleize_slug` to return null, which would revert the behavior in Jekyll

What do you think we should do?

**Comment by mojavelinux** [comment]
Thanks for catching this, @eshepelyuk!

**Comment by eshepelyuk** [comment]
Well, I vote for option #1. Thus, AsciiDoctor doctitile, if presents,  takes precedence over one generated by Jekyll. Seems as quite reasonable and expected behaviour.

**Comment by mojavelinux** [comment]
You are missing one condition of (1). The doctitle will also clobber any title set in the front matter. There's no way we can tell whether the title was auto-generated or specified in the front matter*.

\* Unless we use the logic in (2) or we read the source file and parse the front matter ourselves.

**Comment by eshepelyuk** [comment]
As for me it's fine, i.e. ignoring front matter title if one is present in AsciiDoc document itself.
Maybe we should just add a special note about this behaviour into plugin's docs.

**Comment by eshepelyuk** [comment]
Hello
Excuse me for being bothering, but may I ask what are the resolution intentions for this issue ?

**Comment by mojavelinux** [comment]
Sorry for not replying @eshepelyuk. I had a really busy week and this got pushed back.

I'm kind of torn between (1) and (2). In most cases, (1) is reasonable because it's probably what people use most of the time. However, there are cases where people will want a different page title than document title, and may use the front matter to achieve that (2).

There are other ways to override the title when running under Jekyll. For instance, the author could use a preprocessor conditional to use a different doctitle in the case `env-jekyll` is set. We could also support the `page-title` AsciiDoc attribute as a way to override the title.

Given I see at least two ways to achieve an alternate title, I conclude that we should select (1), but only if a document title (level-0 section title) is specified. We'll also support the `page-title` AsciiDoc attribute as a way to override the title.

Sound reasonable?

**Comment by eshepelyuk** [comment]
Absolutely, thanks for the explanation.

**Comment by mojavelinux** [comment]
Let me know how that works for you, @eshepelyuk.

**Comment by eshepelyuk** [comment]
Issue is fixed, but there's some strange thing happened after using latest plugin version.

Before, I didn't explicitly declared default layout for my posts, i.e. there were no `layout` attribute neither in my FrontMatter nor in `_config.yml`. Somehow, automagically, `_layouts/post.html` was used for my `AsciiDoctor` posts.

Now, after upgrade to `Jekyll3` and latest plugin version - I have to declare default layout in `_config.yml`.

It's not a big deal, reporting it jFYI.

Thanks for bug fix, hope net version will be released soon :)

**Comment by mojavelinux** [comment]
Oops, I made a typo when I refactored. I restored the default layout for posts to "post".

**Comment by eshepelyuk** [comment]
Checked, works as expected :)

**Comment by mojavelinux** [comment]
Awesome! Thanks for testing!
