### ISSUE TITLE
Where are the stylesheets?

### ISSUE THREAD

**Issue by jackphil** [asciidoctor/jekyll-asciidoc#5]
I tried to copy asciidoctor.scss of asciidoctor-stylesheet-factory to the octopress sass/plugins, got the error "File to import not found or unreadable: normalize."

how to use asciidoc in jekyll/octopress with the specific stylesheet?

thanks

**Comment by nerk** [comment]
@jackphil @mojavelinux I just started adding AsciiDoc support incl. styling to the fantastic https://github.com/Phlow/feeling-responsive template. Basically, styling of the original template is unchanged, file **_10_ascciidoc.sass** contains styling for the AsciiDoc specific parts.

In case anybody is interested: https://github.com/nerk/feeling-responsive.git

@Phlow  What about a PR to include this into the original template? AsciiDoc support could be made optional through _config.yml. My AsciiDoc styling could also use some help of someone more inclined towards design.

**Comment by Phlow** [comment]
Hello @nerk – First of thank you for your compliments :) Second: I would happily add your ideas to the original. Unfortunately I just know about ASCIIDOC that you use it for books, right? If you know how to add it via *_config.yml* and enable it, I will add it. My preference would be to turn it off by default, add some information about it in the *_config.yml* and how to use it, why it's there, so users can enable it and use it.

What do you think?

PS: Currently I am working in east asia with slow internet, so it my take some time for my response.

**Comment by nerk** [comment]
Hello @Phlow, I created a pull request. See https://github.com/Phlow/feeling-responsive/pull/102

AsciiDoc is a markup language quite similar to Markdown, but much more powerful and with nicer syntax, IMHO. For more information, please see http://asciidoctor.org and https://github.com/asciidoctor.

After merging and invoking 'bundle install', you should be able to write posts or pages with AsciiDoc markup in addition to Markdown. AsciiDoc support is completely optional, it won't (well, should...) change anything regarding current Markdown support. However, it will install a few additional gems. If we want to avoid this, we need to comment the relevant parts in _config.yml and Gemfile.

Grüße aus Deutschland.

**Comment by Phlow** [comment]
But to use AsciiDoc, you need a plugin, right? It's not compatible with GitHub Pages?!?

**Comment by Phlow** [comment]
I would like to add it.

**Comment by nerk** [comment]
I suggest to move the discusssion over to the https://gihub.com/Phlow/feeling-responsive#102 - I sort of hijacked this issue. I comment over there.

**Comment by nerk** [comment]
If you don't mind, I'll comment this over here https://github.com/Phlow/feeling-responsive/pull/102 - I sort of hijacked this issue.

**Comment by mojavelinux** [comment]
I have recommended the Feeling Responsive theme in the README. Nice work @nerk and @Phlow!

**Comment by Phlow** [comment]
Thankyou for your compliments @mojavelinux :) I love Asciidoc(tor)

**Comment by mojavelinux** [comment]
I love to hear that! As I always say, that just makes me want to make it even more awesome!

Btw, I just released the 2.1.0 version of this plugin.

**Comment by mojavelinux** [comment]
Btw, the quickstart project contains the stylesheet. See https://github.com/asciidoctor/jekyll-asciidoc-quickstart/
