### ISSUE TITLE
Page with no 'asciidoc_page_attribute_prefix' attributes in header fails to be processed

### ISSUE THREAD

**Issue by mkobit** [asciidoctor/jekyll-asciidoc#60]
Noticed this today when writing a new page in `1.1.1`

```
---
---

= Title
my content

```

Fails to be processed with:

```
jekyll-asciidoc-1.1.1/lib/jekyll-asciidoc.rb:109:in `block in generate': undefined method `empty?' for false:FalseClass (NoMethodError)
        from /Users/mkobit/.gem/ruby/2.3.0/gems/jekyll-asciidoc-1.1.1/lib/jekyll-asciidoc.rb:99:in `each'
        from /Users/mkobit/.gem/ruby/2.3.0/gems/jekyll-asciidoc-1.1.1/lib/jekyll-asciidoc.rb:99:in `generate'
```

Which is not very helpful. If the document has an attribute with the prefix (like `page-`):

```
---
---
:page-pizza-topping: pepperoni

= Title
my content 
```

The Jekyll processing seems to work fine (at least with my current `_config.yml`)

It looks to me like the `SafeYAML.load` returns `false` (`FalseClass`) if there is nothing there to load, and then a `Hash` if it is available. This is based on my "debugging" attempt.

Based on my limited research and knowledge, [this StackOverflow answer](http://stackoverflow.com/a/888877/627727) makes it seem that using `.blank?` instead of `.empty?` could fix this, but that seems to only be available in Rails. I'm not sure if hashes are considered "truthy"  or how to treat this. Whatever the idiomatic way is in Ruby, I'd love to do it!

**Comment by mojavelinux** [comment]
Shoot. I had a feeling I was missing something. We should be checking whether the collected attributes are empty, not the final result. I sent a PR to address the issue.

Your assessment is absolutely correct. If you pass an empty string to `SafeYaml.load`, it resolves to `false`. The correct way to safely load with no entries is to add a `---` line at the beginning. However, we can detect when we have no entries and just skip the call to `SafeYaml.load` altogether.

**Comment by eshepelyuk** [comment]
Just experienced exactly the same issue while trying to upgrade. 
@mkobit @mojavelinux Is it possible to release `1.1.2` any time soon ?

**Comment by mkobit** [comment]
@eshepelyuk I can release `1.1.2` tonight.

**Comment by eshepelyuk** [comment]
That would be great, thank you !

**Comment by mojavelinux** [comment]
\o/ Thanks!

**Comment by mkobit** [comment]
@eshepelyuk published `1.1.2`

**Comment by mojavelinux** [comment]
Thanks for doing the release and putting together the release notes @mkobit! I'll announce on Twitter.

**Comment by eshepelyuk** [comment]
Eventually migrated my blog to `Jekyll 3.x` using `1.1.2` version of plugin . Thanks for your efforts !
