### ISSUE TITLE
Random selection of asciidoc files to be rendered

### ISSUE THREAD

**Issue by djalexd** [asciidoctor/jekyll-asciidoc#62]
I can't seem to make lib work properly, are there any gochas? I did a standard / follow instructions bundle install and I've got a couple of files:
* `index.adoc`
* `api.adoc`
* `support.adoc`
(and installed a theme via rubygems).

When I do `bundle exec jekyll serve`, `support.adoc` and `api.adoc` get rendered to HTML, but `index.adoc` remains untouched. Any ideas how I could tackle the issue down? Tried include/exclude, copy pasting the contents, enable debug for more logs, nothing works.

**Comment by mojavelinux** [comment]
You have to add "front matter" to the top of the document, even if it's empty. An empty front matter looks like this:

```
---
---
```

We'd like to get rid of this requirement. That's what we're researching in #57.

**Comment by djalexd** [comment]
@mojavelinux thanks for reply but I don't think this is the topic. All files contain the front matter header, in this format:
```
---
layout: page
permalink: /support
---
```

Can I increase the log level and see what class performs the actual selection (I think, based on file extension `asciidoc_ext: adoc`

**Comment by mojavelinux** [comment]
Thanks for confirming that. With that out of the way, we can look at the next possibility.

By default, it will match files that end in .asciidoc, .adoc or .ad. Yes, the configuration option `asciidoc_ext` overrides that, but it's not necessary unless you are matching some other extension.

To debug, run the following:

```
vim `gem which jekyll-asciidoc`
```

And add the following to line 101:

```
warn ::File.join(page.dir, page.name)
```

That will show you which pages (not posts) the AsciiDoc plugin processes.

I tried with an index.adoc just to be sure it wasn't being excluded and it worked fine for me.

It would be helpful if you could share a project that exhibits this error. That always gets us to a solution fastest.

**Comment by djalexd** [comment]
This is a stripped down version that reproduces the issue:
https://github.com/djalexd/asciidoc-jekyll-test_62

I've also tried your suggestion but doesn't provide much help in logs.
````
vim `gem which jekyll-asciidoc`
````

FYI I tried `bundle exec jekyll serve --verbose --watch` and `jekyll serve --verbose --watch`, is there other option?

**Comment by mojavelinux** [comment]
Thanks. I'll dig in and see if I can figure out what's going on.

> FYI I tried bundle exec jekyll serve --verbose --watch and jekyll serve --verbose --watch, is there other option?

Not that I'm aware of. Though, it does make me realize that perhaps we should add some logging if the `--verbose` flag is set. Can you file a separate issue?

**Comment by djalexd** [comment]
I can file a separate issue, sure.

However, I don't think there is a bug in this plugin, it performs correctly. For some reason, they are considered static files, not pages, by Jekyll, hence their contents is simply copied. Unfortunately, I am really noob at Jekyll / ruby in general, so there's not much output I can work with (e.g. https://github.com/jekyll/jekyll/issues/2650 but I don't see any "render page" output).

I will continue digging

**Comment by djalexd** [comment]
I've updated project `https://github.com/djalexd/asciidoc-jekyll-test_62`, copied file contents from `index.adoc` to `new-api.adoc`. Guess what, `new-api.html` exists while `index.html` not!

**Comment by mojavelinux** [comment]
My original instinct was right. It was just my explanation that was wrong. Some of your AsciiDoc files begin with a BOM (Byte Order Mark). You can see it by opening the file with vim using the `-b` flag.

```
vim -b index.adoc
```

Jekyll is not smart enough to ignore the Byte Order Mark, so it its eyes, the file does not have front matter.

This is likely going to be fixed once we solve #57 because we will drop this whole requirement to have front matter in AsciiDoc files and we will also pass through all AsciiDoc files automatically.

**Comment by mojavelinux** [comment]
I'll add this point to the README.

**Comment by mojavelinux** [comment]
I still think there's good reason to log the files being processed when the `--verbose` flag is set. Had you seen that index.adoc was not in the list of pages being processed, you would have know there was a problem with that file.

**Comment by mojavelinux** [comment]
Documentation updated. Let me know if you think that is clear enough.

https://github.com/asciidoctor/jekyll-asciidoc#creating-pages

**Comment by djalexd** [comment]
Yes, I can confirm that as well :)

I've narrowed the problem down to `jekyll/utils.rb#132-142`:

````
    # Determines whether a given file has
    #
    # Returns true if the YAML front matter is present.
    def has_yaml_header?(file)
      fm = !!(File.open(file, 'rb') { |f| f.readline } =~ /\A---\s*\r?\n/)
      Jekyll.logger.info("FM header on file #{file} is #{fm}")
      fm
    rescue EOFError
      false
    end
````

Based on this (modified) method, I can finally see when Jekyll does not consider those files as pages:
````
FM header on file .asciidoc/index.adoc is false
FM header on file .asciidoc/introduction.adoc is false
FM header on file .asciidoc/new-api.adoc is true
FM header on file .asciidoc/setup.adoc is false
FM header on file .asciidoc/support.adoc is true
````

Probably I need a smarted editor, one that can A. display BOM and B. Remove BOM on demand

**Comment by mojavelinux** [comment]
I'm pretty sure that's the method we're going to overload in this extension so that we can control that decision for AsciiDoc files. Once we do that, and we add logging for pages this converter converts, I think things will become a lot clearer.

**Comment by djalexd** [comment]
I'd like to help with a PR but my ruby skill is practically zero. But still, while this regex `/\A---\s*\r?\n/` in Jekyll core is perfectly fine, I would also check for BOM header (and display a warning in logs). let me know if I can help you out with anything, and thanks a lot for your time and effort.

**Comment by mojavelinux** [comment]
If we take over the has_yaml_header? check, we don't need to worry about the BOM header because Asciidoctor already handles it correctly.

**Comment by mojavelinux** [comment]
I'm going to close this issue as being solved by documentation. The handling of the BOM we'll address in #57.

**Comment by mojavelinux** [comment]
> I still think there's good reason to log the files being processed when the --verbose flag is set. 

As it turns out, Jekyll already does this. However, it only reports files that have front matter header (which is where #57 comes in).

Here's an example:

```
  Rendering: index.adoc
  Pre-Render Hooks: index.adoc
  Rendering Liquid: index.adoc
  Rendering Markup: index.adoc
  Rendering Layout: index.adoc
```

That's pretty detailed information.
