### ISSUE TITLE
Document minimum required version of Jekyll

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#76]
Document the minimum required version of Jekyll. It's currently set as `> 1.0.0` in development. However, I think we should make 2.0.0 the minimum version. A lot of the APIs changes in 2.0.0 and we're starting to have to rely on them.

**Comment by mojavelinux** [comment]
@johncarl81 @eshepelyuk can we bump the minimum version to Jekyll 2.0.0?

**Comment by eshepelyuk** [comment]
LGTM, I've migrated to 3.x branch already.

**Comment by mojavelinux** [comment]
I can't find any instances of a site running Jekyll 1. Most people are on either Jekyll 3 or Jekyll 2.5. I think it's a pretty safe bet.

**Comment by johncarl81** [comment]
Jekyll-Asciidoc-Quickstart is using `gem 'jekyll', '~> 3.1'`
