### ISSUE TITLE
Generation of pages from files without frontmatter does not work

### ISSUE THREAD

**Issue by Gitward** [asciidoctor/jekyll-asciidoc#95]
I'm using `jekyll 3.1.6`, `jekyll-asciidoc 1.1.2` and `asciidoctor 1.5.4`.

In the root of my project I have two files `bar.adoc` and `baz.adoc`.

Running `jekyll build` does generate HTML output from `bar.adoc` but not for `baz.adoc` (instead, baz.adoc is transferred as is to the destination folder `_site`).

## Content of `bar.adoc`

```
---
layout: page
title: Bar Page
permalink: /bar/
---

= A new Asciidoc Page

With Asciidoc content.

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Asciidoctor-Link]

[Markdown-Link](http://kramdown.gettalong.org/syntax.html)
```

## Content of `baz.adoc`

```
= Asciidoc without frontmatter
:page-layout: page
:page-title: Baz Page
:page-permalink: /baz/

With Asciidoc content; without frontmatter.

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Asciidoctor-Link]

[Markdown-Link](http://kramdown.gettalong.org/syntax.html)
```

According to https://github.com/asciidoctor/jekyll-asciidoc#creating-pages both should generate output. **Is there anything wrong with my code?**

**Comment by mojavelinux** [comment]
You jumped the gun a little bit on me. I haven't yet released the version that includes this improvement. I'm working on resolving the final issue, then I'm going to push out the release.

I've updated the README to be more clear about which features are only available starting with version 1.2.0.

**Comment by mojavelinux** [comment]
For now, you're going to need to add an empty front matter header:

```
---
---
= Asciidoc without frontmatter
:page-layout: page
:page-title: Baz Page
:page-permalink: /baz/

With Asciidoc content; without frontmatter.
```

**Comment by mojavelinux** [comment]
I invite you to test the latest code in master. Please follow the steps in the Development section of the README to get started.

**Comment by Gitward** [comment]
Thanks for updating.
I also tried to add 

```
asciidoc:
  require_front_matter_header: false
```
to my `_config.yml`. This gave an error:

```
Invalid Asciidoc processor: {"require_front_matter_header"=>false}
  Valid options are [ asciidoctor ]
jekyll 3.1.6 | Error: uninitialized constant Jekyll::Converters::AsciiDocConverter::FatalException
Did you mean?  Signal Exception
```

I haven't tried it with the latest code - any idea why this happens?

**Comment by mojavelinux** [comment]
Again, you are trying features that aren't yet released.

**Comment by Gitward** [comment]
What's your estimation of when `1.2.0`/`2.0.0` will be released? A week, a month, a year?

**Comment by mojavelinux** [comment]
I'm trying to release it as soon as I possibly can. My goal is this week. I just need to finish resolving #59.

**Comment by Gitward** [comment]
That sounds great.

**Comment by mojavelinux** [comment]
:+1: 

I made good progress tonight. We're super close...and with over 50 tests to verify!
